# Generated by Django 5.2.5 on 2025-08-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electriccars',
            name='encar_id',
            field=models.BigIntegerField(unique=True, verbose_name='Внутреннее id encar'),
        ),
    ]
