# Generated by Django 5.2.5 on 2025-08-21 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0002_alter_electriccars_encar_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electriccars',
            name='encar_id',
            field=models.BigIntegerField(verbose_name='Внутреннее id encar'),
        ),
    ]
