# Generated by Django 5.2.5 on 2025-08-21 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0003_alter_electriccars_encar_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForeignCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encar_id', models.BigIntegerField(verbose_name='Внутреннее id encar')),
                ('url', models.URLField()),
                ('category', models.CharField(max_length=1)),
                ('trust_service', models.CharField(max_length=50)),
                ('inspection', models.BooleanField(default=False)),
                ('record', models.BooleanField(default=False)),
                ('resume', models.BooleanField(default=False)),
                ('photo_url', models.CharField(max_length=256)),
                ('number_of_photos', models.IntegerField()),
                ('manufacturer', models.CharField(max_length=128)),
                ('model', models.CharField(max_length=128)),
                ('version', models.CharField(max_length=128)),
                ('version_details', models.CharField(max_length=128)),
                ('transmission', models.CharField(max_length=128)),
                ('release_date', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('price', models.BigIntegerField()),
                ('sell_type', models.CharField(max_length=128)),
                ('updated', models.DateTimeField()),
                ('city', models.CharField(max_length=128)),
                ('showroom_name', models.CharField(max_length=256)),
                ('dealer_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='KoreanCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encar_id', models.BigIntegerField(verbose_name='Внутреннее id encar')),
                ('url', models.URLField()),
                ('category', models.CharField(max_length=1)),
                ('trust_service', models.CharField(max_length=50)),
                ('inspection', models.BooleanField(default=False)),
                ('record', models.BooleanField(default=False)),
                ('resume', models.BooleanField(default=False)),
                ('photo_url', models.CharField(max_length=256)),
                ('number_of_photos', models.IntegerField()),
                ('manufacturer', models.CharField(max_length=128)),
                ('model', models.CharField(max_length=128)),
                ('version', models.CharField(max_length=128)),
                ('version_details', models.CharField(max_length=128)),
                ('transmission', models.CharField(max_length=128)),
                ('release_date', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('price', models.BigIntegerField()),
                ('sell_type', models.CharField(max_length=128)),
                ('updated', models.DateTimeField()),
                ('city', models.CharField(max_length=128)),
                ('showroom_name', models.CharField(max_length=256)),
                ('dealer_name', models.CharField(max_length=256)),
            ],
        ),
    ]
