# Generated by Django 5.2.5 on 2025-08-21 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0004_foreigncar_koreancar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ElectricCars',
            new_name='ElectricCar',
        ),
    ]
