# Generated by Django 5.2.5 on 2025-08-22 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0005_rename_electriccars_electriccar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ForeignCar',
            new_name='Car',
        ),
        migrations.DeleteModel(
            name='ElectricCar',
        ),
        migrations.DeleteModel(
            name='KoreanCar',
        ),
    ]
