# Generated by Django 5.2.5 on 2025-08-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0006_rename_foreigncar_car_delete_electriccar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='encar_id',
            field=models.BigIntegerField(unique=True, verbose_name='Внутреннее id encar'),
        ),
    ]
