# Generated by Django 5.2.5 on 2025-08-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0007_alter_car_encar_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encar_id', models.BigIntegerField(unique=True, verbose_name='Внутреннее id encar')),
                ('url', models.URLField()),
                ('category', models.CharField(max_length=1)),
                ('trust_service', models.CharField(max_length=50)),
                ('inspection', models.BooleanField(default=False)),
                ('record', models.BooleanField(default=False)),
                ('resume', models.BooleanField(default=False)),
                ('photo_url', models.CharField(max_length=256)),
                ('number_of_photos', models.IntegerField()),
                ('manufacturer', models.CharField(max_length=128)),
                ('model', models.CharField(max_length=128)),
                ('version', models.CharField(max_length=128)),
                ('version_details', models.CharField(max_length=128)),
                ('capacity', models.IntegerField()),
                ('transmission', models.CharField(max_length=128)),
                ('fuel_type', models.CharField(choices=[('G', 'Бензин'), ('D', 'Дизель'), ('L', 'Газ'), ('GE', 'Бензин + Электро'), ('DE', 'Дизель + Электро'), ('LE', 'Газ + Электро'), ('LG', 'Газ + Бензин'), ('E', 'Электро'), ('HY', 'Водород')], default='G', max_length=2)),
                ('release_date', models.IntegerField()),
                ('model_year', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('price', models.BigIntegerField()),
                ('usage', models.CharField(max_length=128)),
                ('updated', models.DateTimeField()),
                ('city', models.CharField(max_length=128)),
                ('showroom_name', models.CharField(max_length=256)),
                ('dealer_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('G', 'Бензин'), ('D', 'Дизель'), ('L', 'Газ'), ('GE', 'Бензин + Электро'), ('DE', 'Дизель + Электро'), ('LE', 'Газ + Электро'), ('LG', 'Газ + Бензин'), ('E', 'Электро'), ('HY', 'Водород')], default='G', max_length=2),
        ),
        migrations.AddField(
            model_name='car',
            name='model_year',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
