# Generated by Django 5.2.5 on 2025-08-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0008_truck_car_fuel_type_car_model_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='capacity',
            field=models.CharField(max_length=32),
        ),
    ]
