# Generated by Django 5.2.5 on 2025-08-23 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0010_optioncategory_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encar_id', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=128)),
                ('vechile', models.CharField(choices=[('CAR', 'CAR'), ('TRUCK', 'TRUCK')], max_length=5)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parser.optioncategory')),
            ],
        ),
        migrations.DeleteModel(
            name='Option',
        ),
    ]
