# Generated by Django 5.2.5 on 2025-08-23 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0011_caroption_delete_option'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarOption',
            new_name='Option',
        ),
    ]
