# Generated by Django 5.2.5 on 2025-08-23 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0013_optioncategory_vechile_caroption_truckoption_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truck',
            name='dealer_name',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='showroom_name',
        ),
    ]
