# Generated by Django 5.2.5 on 2025-08-24 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0015_car_color_truck_color_alter_car_manufacturer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='engine_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='engine_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
