# Generated by Django 5.2.5 on 2025-08-24 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0016_car_engine_capacity_truck_engine_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='horse_power',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
