# Generated by Django 5.2.5 on 2025-08-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0017_truck_horse_power'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='options',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='options',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
