# Generated by Django 5.2.5 on 2025-08-24 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0018_car_options_truck_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='dealer_name',
        ),
        migrations.RemoveField(
            model_name='car',
            name='showroom_name',
        ),
    ]
