# Generated by Django 5.2.5 on 2025-08-26 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0019_remove_car_dealer_name_remove_car_showroom_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='number_of_photos',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='number_of_photos',
        ),
        migrations.AddField(
            model_name='car',
            name='photos_codes',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='photos_codes',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
