# Generated by Django 5.2.5 on 2025-08-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0020_remove_car_number_of_photos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='korean_number',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='korean_number',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
