# Generated by Django 5.2.5 on 2025-08-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0021_car_korean_number_truck_korean_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='dummy_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
