# Generated by Django 5.2.5 on 2025-08-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0022_car_dummy_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='dummy_id',
            field=models.IntegerField(default=0),
        ),
    ]
