# Generated by Django 5.2.5 on 2025-08-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0023_alter_car_dummy_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='dummy_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
