# Generated by Django 5.2.5 on 2025-08-26 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0024_alter_car_dummy_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_front_door', models.CharField(choices=[('НОРМ.', 'НОРМ.'), ('ЗАМЕНА', 'ЗАМЕНА')], max_length=16)),
                ('left_back_door', models.CharField(choices=[('НОРМ.', 'НОРМ.'), ('ЗАМЕНА', 'ЗАМЕНА')], max_length=16)),
                ('right_front_door', models.CharField(choices=[('НОРМ.', 'НОРМ.'), ('ЗАМЕНА', 'ЗАМЕНА')], max_length=16)),
                ('right_back_door', models.CharField(choices=[('НОРМ.', 'НОРМ.'), ('ЗАМЕНА', 'ЗАМЕНА')], max_length=16)),
                ('trunk', models.CharField(choices=[('НОРМ.', 'НОРМ.'), ('ЗАМЕНА', 'ЗАМЕНА')], max_length=16)),
                ('hood', models.CharField(choices=[('НОРМ.', 'НОРМ.'), ('ЗАМЕНА', 'ЗАМЕНА')], max_length=16)),
                ('front_fender_right', models.CharField(choices=[('НОРМ.', 'НОРМ.'), ('ЗАМЕНА', 'ЗАМЕНА')], max_length=16)),
                ('front_fender_left', models.CharField(choices=[('НОРМ.', 'НОРМ.'), ('ЗАМЕНА', 'ЗАМЕНА')], max_length=16)),
                ('vechile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='parser.car')),
            ],
        ),
    ]
