# Generated by Django 5.2.5 on 2025-08-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0025_diagnosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='encar_diag',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
