# Generated by Django 5.2.5 on 2025-08-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0026_truck_encar_diag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truck',
            name='encar_diag',
        ),
        migrations.AddField(
            model_name='car',
            name='encar_diag',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
