# Generated by Django 5.2.5 on 2025-08-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0027_remove_truck_encar_diag_car_encar_diag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='encar_diag',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
