# Generated by Django 5.2.5 on 2025-08-26 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0028_alter_car_encar_diag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='vechile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis', to='parser.car'),
        ),
    ]
