# Generated by Django 5.2.5 on 2025-08-27 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0029_alter_diagnosis_vechile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosis',
            name='vechile',
        ),
        migrations.AddField(
            model_name='car',
            name='diagnosis',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parser.diagnosis'),
            preserve_default=False,
        ),
    ]
