# Generated by Django 5.2.5 on 2025-08-27 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0031_alter_diagnosis_front_fender_left_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='diagnosis',
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis', to='parser.car'),
        ),
    ]
