# Generated by Django 5.2.5 on 2025-08-27 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0032_remove_car_diagnosis_diagnosis_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='car',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parser.car'),
        ),
    ]
