# Generated by Django 5.2.5 on 2025-08-27 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0033_alter_diagnosis_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='dummy_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
