# Generated by Django 5.2.5 on 2025-08-27 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0034_alter_car_dummy_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='car',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis', to='parser.car'),
        ),
    ]
