# Generated by Django 5.2.5 on 2025-08-27 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0035_alter_diagnosis_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_count', models.IntegerField()),
                ('other_accident_cost', models.IntegerField(default=0)),
                ('other_accident_count', models.IntegerField(default=0)),
                ('driver_accident_cost', models.IntegerField(default=0)),
                ('driver_accident_count', models.IntegerField(default=0)),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='car_record', to='parser.car')),
            ],
        ),
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_accident', models.CharField(max_length=256)),
                ('date', models.DateField()),
                ('insurance_benefit', models.IntegerField(default=0)),
                ('part_cost', models.IntegerField(default=0)),
                ('labor_cost', models.IntegerField(default=0)),
                ('painting_cost', models.IntegerField(default=0)),
                ('car_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parser.carrecord')),
            ],
        ),
    ]
