# Generated by Django 5.2.5 on 2025-08-28 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0036_carrecord_accident'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='ru_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
