# Generated by Django 5.2.5 on 2025-08-28 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0037_car_ru_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='encar_id',
            field=models.BigIntegerField(db_index=True, unique=True, verbose_name='Внутреннее id encar'),
        ),
    ]
