# Generated by Django 5.2.5 on 2025-08-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0038_alter_car_encar_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='encar_id',
            field=models.BigIntegerField(unique=True, verbose_name='Внутреннее id encar'),
        ),
    ]
