# Generated by Django 5.2.5 on 2025-08-29 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0039_alter_car_encar_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accident',
            name='type_of_accident',
            field=models.CharField(choices=[('1', 'Урегулировано страховой владельца данного авто'), ('2', 'Возмещение за счет страховой виновника'), ('3', 'С ущербом чужому здоровью или имуществу')], max_length=1),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='front_fender_left',
            field=models.CharField(choices=[('N', 'НОРМ.'), ('R', 'ЗАМЕНА')], max_length=16),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='front_fender_right',
            field=models.CharField(choices=[('N', 'НОРМ.'), ('R', 'ЗАМЕНА')], max_length=16),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='hood',
            field=models.CharField(choices=[('N', 'НОРМ.'), ('R', 'ЗАМЕНА')], max_length=16),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='left_back_door',
            field=models.CharField(choices=[('N', 'НОРМ.'), ('R', 'ЗАМЕНА')], max_length=16),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='left_front_door',
            field=models.CharField(choices=[('N', 'НОРМ.'), ('R', 'ЗАМЕНА')], max_length=16),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='right_back_door',
            field=models.CharField(choices=[('N', 'НОРМ.'), ('R', 'ЗАМЕНА')], max_length=16),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='right_front_door',
            field=models.CharField(choices=[('N', 'НОРМ.'), ('R', 'ЗАМЕНА')], max_length=16),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='trunk',
            field=models.CharField(choices=[('N', 'НОРМ.'), ('R', 'ЗАМЕНА')], max_length=16),
        ),
    ]
