# Generated by Django 5.2.5 on 2025-08-29 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0040_alter_accident_type_of_accident_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='front_fender_left',
            field=models.CharField(choices=[('NORMAL', 'НОРМ.'), ('REPLACEMENT', 'ЗАМЕНА')], max_length=16),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='front_fender_right',
            field=models.CharField(choices=[('NORMAL', 'НОРМ.'), ('REPLACEMENT', 'ЗАМЕНА')], max_length=16),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='hood',
            field=models.CharField(choices=[('NORMAL', 'НОРМ.'), ('REPLACEMENT', 'ЗАМЕНА')], max_length=16),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='left_back_door',
            field=models.CharField(choices=[('NORMAL', 'НОРМ.'), ('REPLACEMENT', 'ЗАМЕНА')], max_length=16),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='left_front_door',
            field=models.CharField(choices=[('NORMAL', 'НОРМ.'), ('REPLACEMENT', 'ЗАМЕНА')], max_length=16),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='right_back_door',
            field=models.CharField(choices=[('NORMAL', 'НОРМ.'), ('REPLACEMENT', 'ЗАМЕНА')], max_length=16),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='right_front_door',
            field=models.CharField(choices=[('NORMAL', 'НОРМ.'), ('REPLACEMENT', 'ЗАМЕНА')], max_length=16),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='trunk',
            field=models.CharField(choices=[('NORMAL', 'НОРМ.'), ('REPLACEMENT', 'ЗАМЕНА')], max_length=16),
        ),
    ]
