# Generated by Django 5.2.5 on 2025-08-29 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0041_alter_diagnosis_front_fender_left_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='category',
        ),
        migrations.RemoveField(
            model_name='car',
            name='trust_service',
        ),
    ]
