# Generated by Django 5.2.5 on 2025-08-29 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0042_remove_car_category_remove_car_trust_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_capacity',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('G', 'Бензин'), ('D', 'Дизель'), ('L', 'Газ'), ('GE', 'Бензин + Электро'), ('DE', 'Дизель + Электро'), ('LE', 'Газ + Электро'), ('LG', 'Газ + Бензин'), ('E', 'Электро'), ('HY', 'Водород')], db_index=True, default='G', max_length=2),
        ),
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='release_date',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(db_index=True, max_length=128),
        ),
    ]
