# Generated by Django 5.2.5 on 2025-08-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0043_alter_car_color_alter_car_engine_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='customs_duty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='recycling_fee',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
