# Generated by Django 5.2.5 on 2025-09-06 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0044_car_customs_duty_car_recycling_fee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Diagnosis',
            new_name='CarDiagnosis',
        ),
        migrations.CreateModel(
            name='TruckDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_front_door', models.CharField(choices=[('NORMAL', 'НОРМ.'), ('REPLACEMENT', 'ЗАМЕНА')], max_length=16)),
                ('left_back_door', models.CharField(choices=[('NORMAL', 'НОРМ.'), ('REPLACEMENT', 'ЗАМЕНА')], max_length=16)),
                ('right_front_door', models.CharField(choices=[('NORMAL', 'НОРМ.'), ('REPLACEMENT', 'ЗАМЕНА')], max_length=16)),
                ('right_back_door', models.CharField(choices=[('NORMAL', 'НОРМ.'), ('REPLACEMENT', 'ЗАМЕНА')], max_length=16)),
                ('trunk', models.CharField(choices=[('NORMAL', 'НОРМ.'), ('REPLACEMENT', 'ЗАМЕНА')], max_length=16)),
                ('hood', models.CharField(choices=[('NORMAL', 'НОРМ.'), ('REPLACEMENT', 'ЗАМЕНА')], max_length=16)),
                ('front_fender_right', models.CharField(choices=[('NORMAL', 'НОРМ.'), ('REPLACEMENT', 'ЗАМЕНА')], max_length=16)),
                ('front_fender_left', models.CharField(choices=[('NORMAL', 'НОРМ.'), ('REPLACEMENT', 'ЗАМЕНА')], max_length=16)),
                ('car', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis', to='parser.truck')),
            ],
        ),
    ]
