# Generated by Django 5.2.5 on 2025-09-06 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0045_rename_diagnosis_cardiagnosis_truckdiagnosis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truck',
            name='category',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='trust_service',
        ),
        migrations.AddField(
            model_name='truck',
            name='dummy_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='encar_diag',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='ru_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
