# Generated by Django 5.2.5 on 2025-09-06 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0046_remove_truck_category_remove_truck_trust_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truck',
            name='ru_price',
        ),
    ]
