# Generated by Django 5.2.5 on 2025-09-06 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0047_remove_truck_ru_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accident',
            new_name='CarAccident',
        ),
        migrations.CreateModel(
            name='TruckRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_count', models.IntegerField()),
                ('other_accident_cost', models.IntegerField(default=0)),
                ('other_accident_count', models.IntegerField(default=0)),
                ('driver_accident_cost', models.IntegerField(default=0)),
                ('driver_accident_count', models.IntegerField(default=0)),
                ('truck', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='truck_record', to='parser.truck')),
            ],
        ),
        migrations.CreateModel(
            name='TruckAccident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_accident', models.CharField(choices=[('1', 'Урегулировано страховой владельца данного авто'), ('2', 'Возмещение за счет страховой виновника'), ('3', 'С ущербом чужому здоровью или имуществу')], max_length=1)),
                ('date', models.DateField()),
                ('insurance_benefit', models.IntegerField(default=0)),
                ('part_cost', models.IntegerField(default=0)),
                ('labor_cost', models.IntegerField(default=0)),
                ('painting_cost', models.IntegerField(default=0)),
                ('truck_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parser.truckrecord')),
            ],
        ),
    ]
