# Generated by Django 5.2.5 on 2025-09-06 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0048_rename_accident_caraccident_truckrecord_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truckrecord',
            name='truck',
        ),
        migrations.DeleteModel(
            name='TruckAccident',
        ),
        migrations.DeleteModel(
            name='TruckRecord',
        ),
    ]
