# Generated by Django 5.2.5 on 2025-09-13 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0049_remove_truckrecord_truck_delete_truckaccident_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField()),
                ('link', models.CharField(max_length=256)),
                ('vechile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parser.car')),
            ],
        ),
    ]
