# Generated by Django 5.2.5 on 2025-09-13 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0050_carphoto_truckphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='photo_url',
        ),
        migrations.RemoveField(
            model_name='car',
            name='photos_codes',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='photo_url',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='photos_codes',
        ),
    ]
