# Generated by Django 5.2.5 on 2025-09-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0051_remove_car_photo_url_remove_car_photos_codes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='body_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
