# Generated by Django 5.2.5 on 2025-09-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0053_carbody_carcolor_truckbody_truckcolor_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TruckBody',
        ),
        migrations.DeleteModel(
            name='TruckColor',
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['body_name', 'model_year'], name='parser_car_body_na_74a38c_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['manufacturer', 'model'], name='parser_car_manufac_ea0b6b_idx'),
        ),
    ]
