# Generated by Django 5.2.5 on 2025-09-19 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0054_delete_truckbody_delete_truckcolor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarFuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_key', models.CharField(max_length=32, unique=True)),
                ('value_name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarManufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_key', models.CharField(max_length=32, unique=True)),
                ('value_name', models.CharField(max_length=32, unique=True)),
                ('car_count', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
