# Generated by Django 5.2.5 on 2025-09-19 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0056_alter_car_fuel_type'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='car',
            new_name='parser_car_manufac_f55022_idx',
            old_name='parser_car_manufac_ea0b6b_idx',
        ),
        migrations.AlterField(
            model_name='car',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parser.carmanufacturer'),
        ),
    ]
