# Generated by Django 5.2.5 on 2025-09-24 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0057_rename_parser_car_manufac_ea0b6b_idx_parser_car_manufac_f55022_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
