# Generated by Django 5.2.5 on 2025-09-27 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0058_car_is_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmanufacturer',
            name='is_foreign',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='carmanufacturer',
            name='name',
            field=models.CharField(default=1, max_length=32, verbose_name='Правильное имя машины'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='release_date',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='carmanufacturer',
            name='car_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Кол-во машин'),
        ),
        migrations.AlterField(
            model_name='carmanufacturer',
            name='value_key',
            field=models.CharField(max_length=32, unique=True, verbose_name='Имя для запроса'),
        ),
        migrations.AlterField(
            model_name='carmanufacturer',
            name='value_name',
            field=models.CharField(max_length=32, unique=True, verbose_name='Имя с encar'),
        ),
    ]
