# Generated by Django 5.2.5 on 2025-11-04 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0059_carmanufacturer_is_foreign_carmanufacturer_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_cost', models.IntegerField(default=1200, verbose_name='Стоимость доставки (В $)')),
                ('extra_expenses', models.IntegerField(default=0, verbose_name='Доп. расходы (необязательно)')),
                ('rate', models.IntegerField(default=80, verbose_name='Курс')),
                ('asia_services', models.IntegerField(default=4, verbose_name='Услуги Asia Alliance (В %)')),
                ('dealer_services', models.IntegerField(default=0, verbose_name='Услуги дилера')),
                ('korea_invoice', models.IntegerField(default=0, verbose_name='Стоимость по инвойсу в Корее')),
                ('broker_cost', models.IntegerField(default=115000, verbose_name='Услуги брокера / СВХ / Лаборатория (В руб.)')),
            ],
        ),
    ]
