# Generated by Django 5.2.5 on 2025-11-18 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0060_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorsePower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_full_name', models.CharField(db_index=True, max_length=256)),
                ('hp', models.IntegerField(default=0)),
            ],
        ),
    ]
