# Generated by Django 5.2.5 on 2025-11-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0061_horsepower'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='hp',
            field=models.IntegerField(default=0),
        ),
    ]
