# Generated by Django 5.2.5 on 2025-11-29 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0062_car_hp'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='final_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
