# Generated by Django 5.2.5 on 2025-11-30 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0062_car_hp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horsepower',
            name='car_full_name',
        ),
        migrations.AddField(
            model_name='car',
            name='final_price_rub',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horsepower',
            name='engine_capacity',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='horsepower',
            name='model',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='horsepower',
            name='model_year',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='horsepower',
            name='value_name',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='horsepower',
            name='version',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
    ]
