# Generated by Django 5.2.5 on 2025-11-30 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0063_car_final_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='horsepower',
            name='engine_capacity',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='horsepower',
            name='model',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='horsepower',
            name='model_year',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='horsepower',
            name='value_name',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='horsepower',
            name='version',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
    ]
