# Generated by Django 5.2.5 on 2025-12-01 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0063_remove_horsepower_car_full_name_car_final_price_rub_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horsepower',
            name='engine_capacity',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='horsepower',
            name='model',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='horsepower',
            name='model_year',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='horsepower',
            name='value_name',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='horsepower',
            name='version',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
    ]
