# Generated by Django 5.2.5 on 2025-11-30 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0064_horsepower_engine_capacity_horsepower_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horsepower',
            name='car_full_name',
        ),
    ]
