# Generated by Django 5.2.5 on 2025-12-13 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0064_alter_horsepower_engine_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='hp_in_kw',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='car',
            name='kw',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='horsepower',
            name='hp_in_kw',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='horsepower',
            name='kw',
            field=models.IntegerField(default=0),
        ),
    ]
