# Generated by Django 5.2.5 on 2025-12-13 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0065_car_hp_in_kw_car_kw_horsepower_hp_in_kw_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='hp_in_kw',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='car',
            name='kw',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='horsepower',
            name='hp_in_kw',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='horsepower',
            name='kw',
            field=models.FloatField(default=0),
        ),
    ]
