# Generated by Django 5.2.5 on 2026-02-10 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0066_alter_car_hp_in_kw_alter_car_kw_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='broker_cost_bishkek',
            field=models.IntegerField(default=1000, verbose_name='Услуги брокера в Бишкеке (В $)'),
        ),
        migrations.AddField(
            model_name='config',
            name='delivery_cost_bishkek_moscow',
            field=models.IntegerField(default=1500, verbose_name='Стоимость доставки из Бишкека в Москву (В $)'),
        ),
        migrations.AddField(
            model_name='config',
            name='delivery_cost_korea_bishkek',
            field=models.IntegerField(default=4000, verbose_name='Стоимость доставки из Кореи в Бишкек (В $)'),
        ),
        migrations.AlterField(
            model_name='horsepower',
            name='hp_in_kw',
            field=models.FloatField(default=0, null=True),
        ),
    ]
