# Generated by Django 5.2.5 on 2026-02-10 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0067_config_broker_cost_bishkek_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='lab_moscow',
            field=models.IntegerField(default=50000, verbose_name='Лаборатория в Москве (В руб.)'),
        ),
    ]
