import requests
import math
from .models import Car, Truck

diagnosis = 'https://api.encar.com/v1/readside/diagnosis/vehicle/40286929'

car_info = 'https://api.encar.com/v1/readside/vehicle/40165677'

photos = 'https://ci.encar.com/carpicture/carpicture03/pic4003/40034021_001.jpg?impolicy=heightRate&rh=696&cw=1160&ch=696&cg=Center&wtmk=https://ci.encar.com/wt_mark/w_mark_04.png'


class CarParser():
    def __init__(self):
        self.current_mileage = 0
        self.current_page = 0
        self.url_dict = {
            'electro_url': ['https://api.encar.com/search/car/list/premium?count=True&q=(And.Hidden.N._.CarType.A._.GreenType.Y._.(Or.Separation.A._.Separation.B.)_.Mileage.range(', '0', '..', '10000', ').)&sr=%7CModifiedDate%7C', '0', '%7C1000'],
            'import_url': ['https://api.encar.com/search/car/list/premium?count=True&q=(And.Hidden.N._.CarType.N._.(Or.Separation.A._.Separation.F._.Separation.B.)_.SellType.%EC%9D%BC%EB%B0%98._.Mileage.range(', '0', '..', '10000', ').)&sr=%7CModifiedDate%7C', '0', '%7C1000'],
            'native_url': ['https://api.encar.com/search/car/list/premium?count=True&q=(And.Hidden.N._.CarType.Y._.(Or.Separation.A._.Separation.B.)_.SellType.%EC%9D%BC%EB%B0%98._.Mileage.range(', '0', '..', '10000', ').)&sr=%7CModifiedDate%7C', '0', '%7C1000']
        }
        self.current_api_url_list = []
        self.session = requests.Session()
        self.headers = {
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36",
                    "Referer": "https://www.encar.com/",
                    "Accept": "application/json, text/plain, */*",
        }
        self.all_ids = set()
        self.new_elems = []

    def run(self):
        self.get_cookies()
        print('Куки получены')
        self.go_through_urls()
        self.session.close()


    def go_through_urls(self):
        '''Функция прохода через все url легковых машин'''
        for api_url_list in self.url_dict.values():
            self.current_api_url_list = api_url_list
            self.get_number_of_results()
            self.go_through_all_mileages()
            self.save_to_db()


    def go_through_all_mileages(self):
        '''Функция прохода через все пробеги легковых машин'''
        for mileage in range(0, 1000000, 10000):
            self.current_api_url_list[1] = str(mileage)
            self.current_api_url_list[3] = str(mileage + 10000)
            print(f'Пробег: от {self.current_api_url_list[1]} до {self.current_api_url_list[3]}')
            self.go_through_all_pages_of_mileage()
        self.current_api_url_list[1] = '0'
        self.current_api_url_list[3] = '10000'


    def go_through_all_pages_of_mileage(self):
        '''Функция прохода через все страницы определенного пробега легковых машин'''
        number_of_results = self.get_number_of_results()
        for page in range(math.ceil(number_of_results/1000)):
            self.current_api_url_list[-2] = str(page*1000)
            response = self.session.get(''.join(self.current_api_url_list), headers=self.headers)    
            data = response.json()['SearchResults']
            print(f'Всего - {response.json()['Count']} Страница {page}. Количество элементов - {len(data)}')
            self.dump_data(data)
        self.current_api_url_list[-2] = '0'


    def dump_data(self, data):
         for elem in data:
            flag_inspection = False
            flag_record = False
            flag_resume = False
            if 'Inspection' in list(elem['Condition']): flag_inspection=True
            if 'Record' in list(elem['Condition']): flag_record=True
            if 'Resume' in list(elem['Condition']): flag_resume=True
            self.new_elems.append(Car(encar_id=elem['Id'],
                                        url=f'https://fem.encar.com/cars/detail/{elem['Id']}',
                                        category=elem.get('Separation', ''),
                                        trust_service=elem.get('Trust', ''),
                                        inspection=flag_inspection,
                                        record=flag_record,
                                        resume=flag_resume,
                                        photo_url=elem.get('Photo', ''),
                                        number_of_photos=0,
                                        # manufacturer=elem.get('Manufacturer', ''),
                                        # model=elem.get('Model', ''),
                                        # version=elem.get('Badge', ''),
                                        # version_details=elem.get('BadgeDetail', ''),
                                        transmission=elem.get('Transmission', ''),
                                        fuel_type = elem.get('FuelType', ''),
                                        release_date = elem.get('Year', 0),
                                        model_year = elem.get('FormYear', 0),
                                        mileage = elem.get('Mileage', 0),
                                        price = elem.get('Price', 0),
                                        sell_type = elem.get('SellType', ''),
                                        updated = elem.get('ModifiedDate', ''),
                                        city = elem.get('OfficeCityState', ''),
                                        showroom_name = elem.get('OfficeName', ''),
                                        dealer_name = elem.get('DealerName', ''),
                                        ))

    def get_cookies(self):
        self.session.get("https://www.encar.com", headers=self.headers) 

    def get_number_of_results(self): #он может найти больше 23 тысяч результатов, но в query никогда их не выдаст, потолок - 10000
        return self.session.get(''.join(self.current_api_url_list), headers=self.headers).json()['Count']

    def save_to_db(self):
        Car.objects.bulk_create(self.new_elems, ignore_conflicts=True)
        self.new_elems = []








class TruckParser():
    def __init__(self):
        self.current_mileage = 0
        self.current_page = 0
        self.url_dict = {
            'truck_url': ['https://api.encar.com/search/truck/list/premium?count=True&q=(And.Hidden.N._.(Or.Separation.A._.Separation.B.)_.Mileage.range(', '0', '..', '50000', ').)&sr=%7CModifiedDate%7C', '0', '%7C1000'],
            }
        self.current_api_url_list = []
        self.session = requests.Session()
        self.headers = {
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36",
                    "Referer": "https://www.encar.com/",
                    "Accept": "application/json, text/plain, */*",
        }
        self.all_ids = set()
        self.new_elems = []

    def run(self):
        self.get_cookies()
        print('Куки получены')
        self.go_through_urls()
        self.session.close()


    def go_through_urls(self):
        '''Функция прохода через все url легковых машин'''
        for api_url_list in self.url_dict.values():
            self.current_api_url_list = api_url_list
            self.get_number_of_results()
            self.go_through_all_mileages()
            self.save_to_db()


    def go_through_all_mileages(self):
        '''Функция прохода через все пробеги легковых машин'''
        for mileage in range(0, 2000000, 50000):
            self.current_api_url_list[1] = str(mileage)
            self.current_api_url_list[3] = str(mileage + 50000)
            print(f'Пробег: от {self.current_api_url_list[1]} до {self.current_api_url_list[3]}')
            self.go_through_all_pages_of_mileage()
        self.current_api_url_list[1] = '0'
        self.current_api_url_list[3] = '50000'


    def go_through_all_pages_of_mileage(self):
        '''Функция прохода через все страницы определенного пробега легковых машин'''
        number_of_results = self.get_number_of_results()
        for page in range(math.ceil(number_of_results/1000)):
            self.current_api_url_list[-2] = str(page*1000)
            response = self.session.get(''.join(self.current_api_url_list), headers=self.headers)    
            data = response.json()['SearchResults']
            print(f'Всего - {response.json()['Count']} Страница {page}. Количество элементов - {len(data)}')
            self.dump_data(data)
        self.current_api_url_list[-2] = '0'


    def dump_data(self, data):
         for elem in data:
            flag_inspection = False
            flag_record = False
            flag_resume = False
            if 'Inspection' in list(elem['Condition']): flag_inspection=True
            if 'Record' in list(elem['Condition']): flag_record=True
            if 'Resume' in list(elem['Condition']): flag_resume=True
            eng_manufacturer = truck_korean_dict['MANUFACTURERS'].get(elem.get('Manufacturer', ''), elem.get('Manufacturer', ''))
            ru_fuel_type = truck_korean_dict['FUEL_TYPES'].get(elem.get('FuelType', ''), elem.get('FuelType', ''))
            ru_transmission = truck_korean_dict['TRANSMISSIONS'].get(elem.get('Transmission', ''), elem.get('Transmission', ''))
            eng_model = truck_korean_dict['MODELS'].get(elem.get('Model', ''), elem.get('Model', ''))
            eng_version = truck_korean_dict['VERSIONS'].get(elem.get('Badge', ''), elem.get('Badge', ''))
            ru_cities = truck_korean_dict['CITIES'].get(elem.get('OfficeCityState', ''), elem.get('OfficeCityState', ''))
            ru_version_details = truck_korean_dict['VERSION_DETAILS'].get(elem.get('FormDetail', ''), elem.get('FormDetail', ''))
            ru_usage = truck_korean_dict['USAGES'].get(elem.get('Use', ''), elem.get('Use', ''))
            if elem.get('Capacity', '') != '': ru_capacity = f'{elem.get('Capacity', '')[:-1]}т.' 
            else: ru_capacity = ''
            self.new_elems.append(Truck(encar_id=elem['Id'],
                                        url=f'https://fem.encar.com/cars/detail/{elem['Id']}',
                                        category=elem.get('Separation', ''),
                                        trust_service=elem.get('Trust', ''),
                                        inspection=flag_inspection,
                                        record=flag_record,
                                        resume=flag_resume,
                                        photo_url=elem.get('Photo', ''),
                                        number_of_photos=0,
                                        # manufacturer=eng_manufacturer,
                                        # model=eng_model,
                                        # version=eng_version,
                                        # version_details=ru_version_details,
                                        capacity=ru_capacity,
                                        transmission=ru_transmission,
                                        fuel_type = ru_fuel_type,
                                        release_date = elem.get('Year', 0),
                                        model_year = elem.get('FormYear', 0),
                                        mileage = elem.get('Mileage', 0),
                                        price = elem.get('Price', 0),
                                        usage = ru_usage,
                                        updated = elem.get('ModifiedDate', ''),
                                        city = ru_cities,
                                        )
                                    )

    def get_cookies(self):
        self.session.get("https://www.encar.com", headers=self.headers) 

    def get_number_of_results(self): #он может найти больше 23 тысяч результатов, но в query никогда их не выдаст, потолок - 10000
        return self.session.get(''.join(self.current_api_url_list), headers=self.headers).json()['Count']

    def save_to_db(self):
        Truck.objects.bulk_create(self.new_elems, ignore_conflicts=True)
        self.new_elems = []



        



truck_korean_dict = {
    'MANUFACTURERS' : {
        "이베코": "Iveco",
        "피아트": "Fiat",
        "스카니아": "Scania",
        "타타대우": "Tata Daewoo",
        "조이롱": "Joylong",
        "한국특장": "Hankook Special Vehicle",
        "Yanmar": "Yanmar",
        "대흥중공업": "Daeheung Heavy Industries",
        "이스즈": "Isuzu",
        "만트럭": "MAN Truck",
        "볼보": "Volvo",
        "선롱": "Sunlong",
        "포드": "Ford",
        "기타": "Other",
        "벤츠": "Mercedes-Benz",
        "현대": "Hyundai",
        "폭스바겐": "Volkswagen",
        "닷지": "Dodge",
        "쌍용": "SsangYong",
        "기아(아시아)": "Kia (Asia)",
        "쉐보레": "Chevrolet",
        "캠핑트레일러": "Camping Trailer",
        "대우버스": "Daewoo Bus",
        "르노삼성": "Renault Samsung"
    },
    'MODELS': {
        "유로카고": "Eurocargo",
        "엘프": "Elf",
        "바인스버그": "Weinsberg",
        "포터": "Porter",
        "라이노": "Rhino",
        "노부스 중형트럭": "Novus Medium Truck",
        "구쎈": "Gussen",
        "크나우스": "Knaus",
        "엘디스": "Elddis",
        "대우버스BC": "Daewoo Bus BC",
        "램": "Ram",
        "포레스트 (포터Ⅱ)": "Forest (Porter II)",
        "대우버스BX": "Daewoo Bus BX",
        "슈퍼에어로시티": "Super Aero City",
        "쏘렌토 R": "Sorento R",
        "봉고프론티어": "Bongo Frontier",
        "더쎈": "The CEN",
        "하비": "Hobby",
        "포터 Ⅱ": "Porter II",
        "마스터": "Master",
        "스위프트": "Swift",
        "뉴그랜버드": "New Granbird",
        "에어밴": "Air Van",
        "포레스트 리버": "Forest River",
        "뉴 카운티": "New County",
        "맥쎈": "Maxcen",
        "LESTAR": "Lestar",
        "스프린터": "Sprinter",
        "그랜드 카니발": "Grand Carnival",
        "프리마 덤프": "Prima Dump",
        "더 뉴 봉고Ⅲ": "The New Bongo III",
        "메가트럭": "Mega Truck",
        "코란도 투리스모": "Korando Turismo",
        "e에어로타운": "e-Aero Town",
        "유니버스": "Universe",
        "코스모스": "Cosmos",
        "노부스 대형트럭": "Novus Heavy Truck",
        "기타": "Other",
        "듀오탑": "Duotop",
        "E시리즈": "E-Series",
        "버스형": "Bus Type",
        "마이티 큐티": "Mighty QT",
        "마이티": "Mighty",
        "데일리": "Daily",
        "싼타페 TM": "Santa Fe TM",
        "AM트럭": "AM Truck",
        "글로벌 900 (그린시티)": "Global 900 (Green City)",
        "카고트럭": "Cargo Truck",
        "스타렉스": "Starex",
        "카운티": "County",
        "스타리아": "Staria",
        "렉스턴 스포츠": "Rexton Sports",
        "현대(슈퍼)트럭": "Hyundai (Super) Truck",
        "프리마 중형트럭": "Prima Medium Truck",
        "렉스턴 스포츠 칸": "Rexton Sports Khan",
        "카니발 R": "Carnival R",
        "복사와이드": "Besta Wide",
        "두카토": "Ducato",
        "비스너": "Büsner",
        "프리마": "Prima",
        "무한괘도식": "Crawler Type",
        "파맥스": "Pamax",
        "노부스 덤프": "Novus Dump",
        "e마이티": "e-Mighty",
        "대형트럭(91A)": "Heavy Truck (91A)",
        "더 뉴 레이": "The New Ray",
        "아드리아": "Adria",
        "올 뉴 마이티": "All New Mighty",
        "더 뉴 카렌스": "The New Carens",
        "대우버스BH": "Daewoo Bus BH",
        "마이티2": "Mighty 2",
        "두에고": "DuEgo",
        "차세대트럭": "Next-Generation Truck",
        "코란도 스포츠": "Korando Sports",
        "더 뉴 카니발": "The New Carnival",
        "네오오토": "NeoAuto",
        "대우버스BS": "Daewoo Bus BS",
        "뉴포터": "New Porter",
        "에어로타운": "Aero Town",
        "뉴파워트럭": "New Power Truck",
        "유니시티": "UniCity",
        "엑시언트": "Xcient",
        "봉고Ⅲ": "Bongo III",
        "e카운티": "e-County",
        "프리마 대형트럭": "Prima Heavy Truck",
        "티볼리 에어": "Tivoli Air",
        "더 뉴 그랜드 스타렉스": "The New Grand Starex",
        "트라고": "Trago",
        "그랜드 스타렉스": "Grand Starex",
        "팰리세이드": "Palisade",
        "덤프": "Dump",
        "세레스": "Ceres",
        "트렌짓": "Transit",
        "대우버스FX": "Daewoo Bus FX",
        "트렉터": "Tractor",
        "리베로": "Libero",
        "카니발 4세대": "Carnival 4th Gen",
        "그랜드 캘리포니아": "Grand California",
        "중형트럭(91A)": "Medium Truck (91A)",
        "E6": "E6",
        "대형트럭": "Heavy Truck",
        "G4 렉스턴": "G4 Rexton",
        "코나": "Kona",
        "쏠라티": "Solati",
        "파비스": "Pavise",
        "익스프레스밴": "Express Van"
    },
    'VERSIONS': {
        "090 25인승": "090 25-seater",
        "럭셔리": "Luxury",
        "롱바디 GOLD 25인승": "Long Body GOLD 25-seater",
        "장축 리무진 11인승": "Long Wheelbase Limousine 11-seater",
        "GOLD": "GOLD",
        "장축 GOLD 29인승": "Long Wheelbase GOLD 29-seater",
        "엘레강스": "Elegance",
        "120 46인승": "120 46-seater",
        "프레미오": "Premio",
        "D500": "D500",
        "표준형 SUP 20인승": "Standard SUP 20-seater",
        "일반캡 LPG": "Standard Cab LPG",
        "106 47인승": "106 47-seater",
        "디젤 42인승": "Diesel 42-seater",
        "일반캡": "Standard Cab",
        "내로우캡": "Narrow Cab",
        "쥐트빈트": "Zitwind",
        "디젤": "Diesel",
        "슈퍼캡 LPG": "Super Cab LPG",
        "스탠다드": "Standard",
        "4WD": "4WD",
        "SUP": "SUP",
        "롱바디 35인승": "Long Body 35-seater",
        "장축 DLX 12인승": "Long Wheelbase DLX 12-seater",
        "더블캡 CRDI": "Double Cab CRDI",
        "4WD 킹캡": "4WD King Cab",
        "롱바디 DLX 39인승": "Long Body DLX 39-seater",
        "터보인터쿨러 일반캡": "Turbo Intercooler Standard Cab",
        "VIO17": "VIO17",
        "디젤 38인승": "Diesel 38-seater",
        "락우드": "Rockwood",
        "장축 리무진 15인승": "Long Wheelbase Limousine 15-seater",
        "초장축 어린이 33인승": "Extra Long Wheelbase Kids 33-seater",
        "8X2": "8X2",
        "롱바디 SUP 29인승": "Long Body SUP 29-seater",
        "롱바디 30인승": "Long Body 30-seater",
        "6X4 저상": "6X4 Low Floor",
        "디젤 46인승": "Diesel 46-seater",
        "장축 어린이 39인승": "Long Wheelbase Kids 39-seater",
        "와이드캡 GOLD": "Wide Cab GOLD",
        "35인승": "35-seater",
        "장축 GOLD 16인승": "Long Wheelbase GOLD 16-seater",
        "바이엘 스마트": "Bayer Smart",
        "슬리퍼캡": "Sleeper Cab",
        "39인승": "39-seater",
        "12인승": "12-seater",
        "표준형 DLX 25인승": "Standard DLX 25-seater",
        "슈퍼캡 TCI": "Super Cab TCI",
        "LPI": "LPI",
        "슈퍼캡 CRDI": "Super Cab CRDI",
        "4WD 더블캡": "4WD Double Cab",
        "표준캡": "Standard Cab",
        "킹캡 TCI": "King Cab TCI",
        "8X4": "8X4",
        "롱바디 23인승": "Long Body 23-seater",
        "4WD 킹캡 LPG": "4WD King Cab LPG",
        "장축 스페셜 25인승": "Long Wheelbase Special 25-seater",
        "장축 GOLD 20인승": "Long Wheelbase GOLD 20-seater",
        "4X4": "4X4",
        "10x4": "10X4",
        "컴포트": "Comfort",
        "090 34인승": "090 34-seater",
        "115 46인승": "115 46-seater",
        "터보인터쿨러 슈퍼캡": "Turbo Intercooler Super Cab",
        "아도라": "Adora",
        "아버소": "Averso",
        "6X4 후삼축": "6X4 Rear Triple Axle",
        "더블캡 LPG": "Double Cab LPG",
        "4WD 표준캡": "4WD Standard Cab",
        "4WD 슈퍼캡 LPG": "4WD Super Cab LPG",
        "단축 STD 25인승": "Short Wheelbase STD 25-seater",
        "롱바디 34인승": "Long Body 34-seater",
        "롱바디 SUP 25인승": "Long Body SUP 25-seater",
        "기타": "Other",
        "20인승": "20-seater",
        "일반캡 CRDI": "Standard Cab CRDI",
        "노블": "Noble",
        "47인승": "47-seater",
        "29인승": "29-seater",
        "장축 어린이 21인승": "Long Wheelbase Kids 21-seater",
        "롱바디 리무진 15인승": "Long Body Limousine 15-seater",
        "슈퍼캡 디젤": "Super Cab Diesel",
        "34인승": "34-seater",
        "표준형 SUP 25인승": "Standard SUP 25-seater",
        "킹캡": "King Cab",
        "데이캡": "Day Cab",
        "212S 42인승": "212S 42-seater",
        "표준캡 LPG": "Standard Cab LPG",
        "8x4": "8X4",
        "표준캡 CRDI": "Standard Cab CRDI",
        "프라임": "Prime",
        "디젤 59인승": "Diesel 59-seater",
        "4WD 더블캡 LPG": "4WD Double Cab LPG",
        "4WD 표준캡 LPG": "4WD Standard Cab LPG",
        "6X2": "6X2",
        "단축 어린이 34인승": "Short Wheelbase Kids 34-seater",
        "카라원 390": "CaraOne 390",
        "장축 투어 15인승": "Long Wheelbase Tour 15-seater",
        "090 35인승": "090 35-seater",
        "212S 45인승": "212S 45-seater",
        "CNG 58인승": "CNG 58-seater",
        "090 67인승": "090 67-seater",
        "장축 SUP 20인승": "Long Wheelbase SUP 20-seater",
        "더블캡 TCI": "Double Cab TCI",
        "장축 SUP 25인승": "Long Wheelbase SUP 25-seater",
        "8X4 후삼축": "8X4 Rear Triple Axle",
        "로얄": "Royal",
        "롱바디 21인승": "Long Body 21-seater",
        "디럭스": "Deluxe",
        "등급 없음": "No Grade",
        "7인승": "7-seater",
        "일렉트릭 33인승": "Electric 33-seater",
        "표준형 SUP 15인승": "Standard SUP 15-seater",
        "090 30인승": "090 30-seater",
        "표준형 STD 25인승": "Standard STD 25-seater",
        "4X2 표준": "4X2 Standard",
        "킹캡 EV": "King Cab EV",
        "42인승": "42-seater",
        "일반캡 TCI": "Standard Cab TCI",
        "6X4": "6X4",
        "18인승": "18-seater",
        "수퍼디럭스": "Super Deluxe",
        "슈퍼캡": "Super Cab",
        "단축 SUP 25인승": "Short Wheelbase SUP 25-seater",
        "롱바디 38인승": "Long Body 38-seater",
        "4WD 일반캡 LPG": "4WD Standard Cab LPG",
        "프리미엄": "Premium",
        "단축 어린이 20인승": "Short Wheelbase Kids 20-seater",
        "슈퍼캡 일렉트릭(EV)": "Super Cab Electric (EV)",
        "표준캡 TCI": "Standard Cab TCI",
        "프레스티지": "Prestige",
        "표준형 30인승": "Standard 30-seater",
        "장축 SUP 29인승": "Long Wheelbase SUP 29-seater",
        "와이드캡 프리미엄": "Wide Cab Premium",
        "표준형 DLX 34인승": "Standard DLX 34-seater",
        "116 46인승": "116 46-seater",
        "롱바디 SUP 24인승": "Long Body SUP 24-seater",
        "10X4": "10X4",
        "표준형 34인승": "Standard 34-seater",
        "어피니티": "Affinity",
        "카라원 480": "CaraOne 480",
        "캠핑카": "Camping Car",
        "8X4": "8X4",
        "25인승": "25-seater",
        "장축 GOLD 25인승": "Long Wheelbase GOLD 25-seater",
        "4WD 일반캡": "4WD Standard Cab",
        "울트라": "Ultra",
        "600": "600",
        "펜타 슬리퍼캡": "Penta Sleeper Cab",
        "장축 어린이 29인승": "Long Wheelbase Kids 29-seater",
        "212H 29인승": "212H 29-seater",
        "스프라이트": "Sprite",
        "GOLD 25인승": "GOLD 25-seater",
        "212 22인승 리무진": "212 22-seater Limousine",
        "더블캡 디젤": "Double Cab Diesel",
        "4x4 일반캡": "4X4 Standard Cab",
        "4WD 슈퍼캡": "4WD Super Cab",
        "SUP 25인승": "SUP 25-seater",
        "4X2": "4X2",
        "더블캡": "Double Cab",
        "19인승": "19-seater",
        "AVT2042He": "AVT2042He",
        "킹캡 CRDI": "King Cab CRDI",
        "일반캡 4WD": "Standard Cab 4WD",
        "CRDI 슈퍼캡": "CRDI Super Cab",
        "단축 DLX 25인승": "Short Wheelbase DLX 25-seater",
        "킹캡 LPG": "King Cab LPG",
        "2WD": "2WD"
    },
    'FUEL_TYPES': {
        "전기": "Электричество",
        "가솔린": "Бензин",
        "LPG(일반인 구입)": "Пропан-бутан (Газ)",
        "디젤": "Дизель",
        "CNG": "Метан (Газ)",
        "기타": "Другое"
    },
    'TRANSMISSIONS': {
        "수동": "Механическая",
        "오토": "Автоматическая",
        "세미오토": "Полуавтоматическая",
        "기타": "Другое"
    },
    'CITIES': {
        "충남": "Чхуннам (пров. Чхунчхон-Намдо)",
        "울산": "Ульсан",
        "광주": "Кванджу",
        "경남": "Кённам (пров. Кёнсан-Намдо)",
        "경기": "Кёнги (пров. Кёнгидо)",
        "강원": "Канвон (пров. Канвондо)",
        "충북": "Чхунбук (пров. Чхунчхон-Пукто)",
        "부산": "Пусан",
        "대구": "Тэгу",
        "경북": "Кёнбук (пров. Кёнсан-Пукто)",
        "전남": "Чолланам (пров. Чолла-Намдо)",
        "인천": "Инчхон",
        "세종": "Седжон",
        "전북": "Чолла-Пукто (Чоллабук)",
        "제주": "Чеджу",
        "서울": "Сеул",
        "대전": "Тэджон",
    },

    'USAGES': {
        "등본차량": "Служебный автомобиль",
        "영업용": "Коммерческий транспорт",
        "자가용": "Личный автомобиль",
    },

    'VERSION_DETAILS' : {
        "음식물수거": "Мусоровоз для пищевых отходов",
        "특수/케미컬(VOC,테플론)탱크로리": "Спецтехника / химический (VOC, тефлон) танкер",
        "오가크레인": "Автокран (O.G.A. кран)",
        "워킹플로어": "Кузов с подвижным полом (Walking Floor)",
        "집게차": "Манипулятор с грейфером",
        "준설차": "Дноочистительная машина / земснаряд",
        "익스(하이)내장탑": "Фургон изотермический (High-EX)",
        "익스(하이)냉장탑": "Рефрижератор (High-EX)",
        "언더리프트": "Эвакуатор с подкатом (Underlift)",
        "저상형 윙바디": "Низкорамный фургон с боковым открытием (Wing body)",
        "사료운반차": "Кормовоз",
        "컨테이너 샤시": "Шасси-контейнеровоз",
        "암롤/롤온": "Мультилифт (Amroll / Roll-on)",
        "냉동탑": "Фургон-рефрижератор (морозильный)",
        "활어차": "Автоцистерна для живой рыбы",
        "살수차": "Поливомоечная машина",
        "이동/광고/응급차": "Передвижная реклама / спецмашина / скорая",
        "익스(하이)내장탑 파워게이트": "Фургон изотермический High-EX с гидробортом",
        "냉동윙": "Фургон-рефрижератор с боковым открытием (Reefer Wing)",
        "이동식 목욕차": "Передвижная баня / душ",
        "냉장윙": "Рефрижераторный фургон (охлаждаемый) с боковым открытием",
        "캠핑트레일러": "Кемпинг-трейлер",
        "카고(화물)트럭": "Грузовой бортовой автомобиль",
        "압착진개": "Мусоровоз-компактор (с прессом)",
        "트렉터": "Тягач (трактор-седельный)",
        "바가지차": "Автокран с ковшом (автовышка-«ковшевик»)",
        "냉동탑 파워게이트": "Фургон-рефрижератор с гидробортом",
        "내장탑 파워게이트": "Изотермический фургон с гидробортом",
        "기타": "Прочее",
        "진개덤프": "Самосвал-мусоровоз",
        "저상형 내장탑": "Низкорамный изотермический фургон",
        "윙바디 파워게이트": "Фургон с боковым открытием (Wing body) и гидробортом",
        "사다리차": "Автолестница",
        "재활용품수집차": "Мусоровоз для раздельного сбора",
        "굴삭기": "Экскаватор",
        "익스(하이)냉동탑 파워게이트": "High-EX рефрижератор с гидробортом",
        "유류/액상탱크로리": "Автоцистерна для ГСМ/жидкостей",
        "저상형 냉장탑": "Низкорамный рефрижератор",
        "캠핑카": "Кемпер (дом на колесах)",
        "저상형 냉동탑": "Низкорамный фургон-рефрижератор (морозильный)",
        "셀프로더": "Самопогрузчик",
        "압축진개": "Мусоровоз-пресс (компрессионный)",
        "노면청소차": "Подметально-уборочная машина",
        "윙바디": "Фургон с боковым открытием (Wing body)",
        "익스(하이)냉동탑": "High-EX фургон-рефрижератор",
        "보냉윙": "Изотермический фургон с боковым открытием",
        "익스(하이)냉장탑 파워게이트": "High-EX рефрижераторный фургон с гидробортом",
        "내장탑": "Изотермический фургон",
        "씨티/워크스루밴": "Сити-вэн / фургон Walk-through",
        "냉온장탑": "Фургон с климат-контролем (тепло-холод)",
        "버스": "Автобус",
        "상승내장탑": "Фургон с подъемным кузовом (Lift-up)",
        "버큠로리": "Вакуумная машина (ассенизатор)",
        "로우베드/릴리리": "Низкорамный трейлер (Low-bed trailer)",
        "활선차(고소작업)": "Автовышка для работы под напряжением",
        "저상형 내장탑 파워게이트": "Низкорамный изотермический фургон с гидробортом",
        "톱밥운반차": "Опилкивоз",
        "다용도탑": "Многофункциональный фургон",
        "냉장탑": "Фургон-рефрижератор (охлаждаемый)",
        "트랜스/와이드 파워게이트": "Широкий фургон с гидробортом (Wide PG)",
        "카케리어": "Автовоз",
        "윙트레일러": "Трейлер с боковым открытием (Wing trailer)",
        "카고크레인": "Бортовой грузовик с краном-манипулятором",
        "파워게이트": "Гидроборт (Power gate)",
        "덤프": "Самосвал",
    }
}



car_korean_dict = {
    'MANUFACTURERS': {
        "도요타": "Toyota",
        "BMW": "BMW",
        "어큐라": "Acura",
        "알파 로메오": "Alfa Romeo",
        "스즈키": "Suzuki",
        "이네오스": "Ineos",
        "로터스": "Lotus",
        "아우디": "Audi",
        "기타 제조사": "Other Manufacturers",
        "뷰익": "Buick",
        "마세라티": "Maserati",
        "KG모빌리티(쌍용)": "KG Mobility (SsangYong)",
        "쉐보레(GM대우)": "Chevrolet (GM Daewoo)",
        "르노코리아(삼성)": "Renault Korea (Samsung)",
        "머큐리": "Mercury",
        "기타 수입차": "Other Imports",
        "폴스타": "Polestar",
        "북기은상": "BAIC Yinxiang",
        "벤틀리": "Bentley",
        "크라이슬러": "Chrysler",
        "마쯔다": "Mazda",
        "미쯔비시": "Mitsubishi",
        "링컨": "Lincoln",
        "테슬라": "Tesla",
        "쉐보레": "Chevrolet",
        "사브": "Saab",
        "BYD": "BYD",
        "시트로엥/DS": "Citroën / DS",
        "동풍소콘": "DFSK (Dongfeng Sokon)",
        "험머": "Hummer",
        "마이바흐": "Maybach",
        "사이언": "Scion",
        "재규어": "Jaguar",
        "기아": "Kia",
        "랜드로버": "Land Rover",
        "스바루": "Subaru",
        "렉서스": "Lexus",
        "캐딜락": "Cadillac",
        "지프": "Jeep",
        "포드": "Ford",
        "GMC": "GMC",
        "혼다": "Honda",
        "벤츠": "Mercedes-Benz",
        "미쯔오까": "Mitsuoka",
        "스마트": "Smart",
        "롤스로이스": "Rolls-Royce",
        "미니": "MINI",
        "제네시스": "Genesis",
        "인피니티": "Infiniti",
        "페라리": "Ferrari",
        "피아트": "Fiat",
        "애스턴마틴": "Aston Martin",
        "닷지": "Dodge",
        "다이하쯔": "Daihatsu",
        "볼보": "Volvo",
        "닛산": "Nissan",
        "람보르기니": "Lamborghini",
        "맥라렌": "McLaren",
        "포르쉐": "Porsche",
        "현대": "Hyundai",
        "폭스바겐": "Volkswagen",
        "푸조": "Peugeot",
        "링야오": "Lynk & Co",
        "쌍용": "SsangYong",
        "재규어랜드로버": "Jaguar Land Rover",
        "GAC": "GAC",
    },
    'MODELS':{
        "207SW": "207SW",
        "S660": "S660",
        "니로 플러스": "Niro Plus",
        "더 뉴 레이": "The New Ray",
        "M2 (G87)": "M2 (G87)",
        "5시리즈 (G30)": "5 Series (G30)",
        "E-클래스 W214": "E-Class W214",
        "쿠퍼 S 컨트리맨": "Cooper S Countryman",
        "650S": "650S",
        "코란도 지프": "Korando Jeep",
        "뉴카니발": "New Carnival",
        "쏘나타 디 엣지 하이브리드(DN8)": "Sonata The Edge Hybrid (DN8)",
        "프리몬트": "Freemont",
        "더 뉴 i40": "The New i40",
        "에스컬레이드 5세대": "Escalade 5th Gen",
        "레인지로버 이보크 2세대": "Range Rover Evoque 2nd Gen",
        "베라크루즈": "Veracruz",
        "SM3 Z.E.": "SM3 Z.E.",
        "모델 S": "Model S",
        "더 뉴 투싼 하이브리드 (NX4)": "The New Tucson Hybrid (NX4)",
        "더 뉴 제네시스 쿠페": "The New Genesis Coupe",
        "S3": "S3",
        "쿠퍼": "Cooper",
        "포포": "Fofor",
        "더 뉴 K3": "The New K3",
        "기타": "Other",
        "그랜저 TG": "Grandeur TG",
        "스포티지 R": "Sportage R",
        "르반떼": "Levante",
        "리프 (ZE1)": "Leaf (ZE1)",
        "MKX": "MKX",
        "5008 2세대": "5008 2nd Gen",
        "포투 카브리오 3세대": "Fortwo Cabrio 3rd Gen",
        "RX450hL 4세대": "RX450hL 4th Gen",
        "더 뉴 G70 슈팅브레이크": "The New G70 Shooting Brake",
        "QX50 (P71A)": "QX50 (P71A)",
        "ES330": "ES330",
        "셀토스": "Seltos",
        "다이너스티": "Dynasty",
        "QX60": "QX60",
        "쿠퍼 D 페이스맨": "Cooper D Paceman",
        "C-클래스": "C-Class",
        "4시리즈 (G22)": "4 Series (G22)",
        "뉴오피러스": "New Opirus",
        "스펙터": "Spectre",
        "i40 살룬": "i40 Saloon",
        "QX70": "QX70",
        "야리스(비츠)": "Yaris (Vitz)",
        "9000": "9000",
        "3008": "3008",
        "이그니스": "Ignis",
        "더 뉴 모하비": "The New Mohave",
        "니로 EV": "Niro EV",
        "타이칸": "Taycan",
        "기블리": "Ghibli",
        "미라 코코아": "Mira Cocoa",
        "LX": "LX",
        "스팅어": "Stinger",
        "뉴카이런": "New Kyron",
        "뉴쏘렌토": "New Sorento",
        "그랜드 스타렉스": "Grand Starex",
        "짐니": "Jimny",
        "윈스톰 맥스": "Winstorm Max",
        "A5": "A5",
        "뉴무쏘": "New Musso",
        "파일럿 4세대": "Pilot 4th Gen",
        "G25": "G25",
        "CLS-클래스 C257": "CLS-Class C257",
        "S8 (D5)": "S8 (D5)",
        "X5M (F15)": "X5M (F15)",
        "940": "940",
        "컴패스": "Compass",
        "그랜저 (GN7)": "Grandeur (GN7)",
        "GS450h": "GS450h",
        "F250": "F250",
        "M3 (E90)": "M3 (E90)",
        "LF 쏘나타": "LF Sonata",
        "스파크": "Spark",
        "뉴코란도": "New Korando",
        "티구안 2세대": "Tiguan 2nd Gen",
        "CLS-클래스 W219": "CLS-Class W219",
        "뉴카렌스": "New Carens",
        "아이오닉 하이브리드": "Ioniq Hybrid",
        "3시리즈 GT (F34)": "3 Series GT (F34)",
        "하이랜더 4세대": "Highlander 4th Gen",
        "뉴 MKS": "New MKS",
        "쏘나타 뉴 라이즈": "Sonata New Rise",
        "더 K9": "The K9",
        "900": "900",
        "프리우스 5세대": "Prius 5th Gen",
        "더 뉴 카렌스": "The New Carens",
        "뉴포텐샤": "New Potentia",
        "MKT": "MKT",
        "디스커버리 4": "Discovery 4",
        "쿠퍼 일렉트릭 4세대": "Cooper Electric 4th Gen",
        "Z3": "Z3",
        "쿠퍼 SD 쿠페": "Cooper SD Coupe",
        "더 뉴 코나 하이브리드": "The New Kona Hybrid",
        "더 뉴 K5": "The New K5",
        "bB": "bB",
        "베르나 트랜스폼": "Verna Transform",
        "LS430": "LS430",
        "All New XJ": "All New XJ",
        "스테이츠맨": "Statesman",
        "F-PACE": "F-PACE",
        "G4 렉스턴": "G4 Rexton",
        "포르테 해치백": "Forte Hatchback",
        "350Z": "350Z",
        "마크2": "Mark 2",
        "407": "407",
        "시에라": "Sierra",
        "X5M (E70)": "X5M (E70)",
        "SM5": "SM5",
        "더 뉴 300C": "The New 300C",
        "아웃랜더": "Outlander",
        "밴티지 2세대": "Vantage 2nd Gen",
        "램픽업": "Ram Pickup",
        "리프": "Leaf",
        "C4 피카소": "C4 Picasso",
        "GS350": "GS350",
        "스빌": "Savil",
        "더 뉴 렉스턴 스포츠 칸": "The New Rexton Sports Khan",
        "더 뉴 카니발 4세대": "The New Carnival 4th Gen",
        "쿠퍼 SD 페이스맨": "Cooper SD Paceman",
        "508SW": "508SW",
        "RC F": "RC F",
        "어메이징 뉴 크루즈": "Amazing New Cruze",
        "더 뉴 기아 레이 EV": "The New Kia Ray EV",
        "CLS-클래스 W218": "CLS-Class W218",
        "2008": "2008",
        "아슬란": "Aslan",
        "봉고III 미니버스": "Bongo III Minibus",
        "더 뉴 스파크": "The New Spark",
        "렉스턴 스포츠": "Rexton Sports",
        "A3 (8Y)": "A3 (8Y)",
        "라비타": "LAvita",
        "아이오닉5": "Ioniq 5",
        "이클립스": "Eclipse",
        "GL-클래스 X164": "GL-Class X164",
        "엘그란드": "Elgrand",
        "뉴 아반떼 XD": "New Avante XD",
        "아투라": "Atura",
        "S-클래스 W221": "S-Class W221",
        "i5 (G60)": "i5 (G60)",
        "ES350": "ES350",
        "G2X": "G2X",
        "올 뉴 K7": "All New K7",
        "더 프레스티지 K7": "The Prestige K7",
        "718 박스터": "718 Boxster",
        "1시리즈 (F40)": "1 Series (F40)",
        "GLS-클래스 X166": "GLS-Class X166",
        "캐피탈": "Capital",
        "Z4 (G29)": "Z4 (G29)",
        "스카이라인": "Skyline",
        "브롱코 6세대": "Bronco 6th Gen",
        "더 뉴 SM6": "The New SM6",
        "모닝": "Morning",
        "골프 4세대": "Golf 4th Gen",
        "체어맨 W": "Chairman W",
        "쿠퍼 컨트리맨": "Cooper Countryman",
        "렉스턴 스포츠 칸": "Rexton Sports Khan",
        "NF 쏘나타 트랜스폼": "NF Sonata Transform",
        "레인저 3세대": "Ranger 3rd Gen",
        "쿠퍼 S 컨버터블 4세대": "Cooper S Convertible 4th Gen",
        "마치": "March",
        "DTS": "DTS",
        "V70": "V70",
        "GLE-클래스 W167": "GLE-Class W167",
        "더 뉴 i30": "The New i30",
        "RAV4 5세대": "RAV4 5th Gen",
        "M-클래스 W164": "M-Class W164",
        "프레스토": "Presto",
        "더 뉴 모닝": "The New Morning",
        "프라이드(신형)": "Pride (New Model)",
        "어벤저": "Avenger",
        "크루즈5": "Cruze5",
        "알파드": "Alphard",
        "750S": "750S",
        "투스카니(신형)": "Tuscani (New)",
        "6시리즈 (F12)": "6 Series (F12)",
        "E-클래스 W210": "E-Class W210",
        "GV70": "GV70",
        "X4M (G02)": "X4M (G02)",
        "718 카이맨": "718 Cayman",
        "LX 4세대": "LX 4th Gen",
        "그랜저 HG 하이브리드": "Grandeur HG Hybrid",
        "뉴 토러스": "New Taurus",
        "뉴 SLK-클래스": "New SLK-Class",
        "쿠퍼 S 컨버터블": "Cooper S Convertible",
        "프리우스 프라임": "Prius Prime",
        "NX300": "NX300",
        "Q70": "Q70",
        "폴로": "Polo",
        "올 뉴 300C": "All New 300C",
        "더 뉴 G70": "The New G70",
        "280ZX": "280ZX",
        "M 쿠페/로드스터 (E85)": "M Coupe/Roadster (E85)",
        "렉스턴 W": "Rexton W",
        "C31": "C31",
        "iX": "iX",
        "5시리즈 (E60)": "5 Series (E60)",
        "RS4": "RS4",
        "모닝 어반 (JA)": "Morning Urban (JA)",
        "4C": "4C",
        "DB11": "DB11",
        "토스카 프리미엄6": "Tosca Premium 6",
        "디펜더 (L663)": "Defender (L663)",
        "X4 (G02)": "X4 (G02)",
        "레인지로버 스포츠 3세대": "Range Rover Sport 3rd Gen",
        "코나": "Kona",
        "M6 (F12)": "M6 (F12)",
        "208": "208",
        "캡처": "Captur",
        "벨로스터": "Veloster",
        "팬텀": "Phantom",
        "골프 5세대": "Golf 5th Gen",
        "아카디아": "Acadia",
        "EQC N293": "EQC N293",
        "FF": "FF",
        "트라제 XG": "Trajet XG",
        "CLA-클래스 C117": "CLA-Class C117",
        "쏘울 부스터": "Soul Booster",
        "에쿠스": "Equus",
        "C32": "C32",
        "C5 에어크로스": "C5 Aircross",
        "V-클래스": "V-Class",
        "그랜드 보이저": "Grand Voyager",
        "더 뉴 싼타페": "The New Santa Fe",
        "FX45": "FX45",
        "FJ 크루져": "FJ Cruiser",
        "SQ5 (FY)": "SQ5 (FY)",
        "X6M (E71)": "X6M (E71)",
        "가류": "G-Class",
        "비틀": "Beetle",
        "투싼 (NX4)": "Tucson (NX4)",
        "코란도 투리스모": "Korando Turismo",
        "V50": "V50",
        "쏘나타 더 브릴리언트": "Sonata The Brilliant",
        "K7 하이브리드": "K7 Hybrid",
        "알페온": "Alpheon",
        "GR86": "GR86",
        "세브링": "Sebring",
        "티코": "Tico",
        "RX350 4세대": "RX350 4th Gen",
        "프리스타일": "Freestyle",
        "싼타페 (MX5)": "Santa Fe (MX5)",
        "볼트(Volt)": "Volt",
        "iX2 (U10)": "iX2 (U10)",
        "폴스타 4": "Polestar 4",
        "XC40 리차지": "XC40 Recharge",
        "프리우스 4세대": "Prius 4th Gen",
        "V40 크로스컨트리": "V40 Cross Country",
        "알토라팡": "Alto Lapin",
        "크루즈": "Cruze",
        "iX1 (U11)": "iX1 (U11)",
        "765LT": "765LT",
        "뉴 비틀": "New Beetle",
        "로체 어드밴스": "Lacetti Advance",
        "S60 크로스컨트리": "S60 Cross Country",
        "이코노라인": "Econoline",
        "매그너스": "Magnus",
        "RDX": "RDX",
        "더 뉴 아이오닉 일렉트릭": "The New Ioniq Electric",
        "모델 3": "Model 3",
        "로마": "Roma",
        "포텐샤": "Potentia",
        "로디우스": "Rodius",
        "X3 (F25)": "X3 (F25)",
        "XKR": "XKR",
        "쥬크": "Juke",
        "CTS-V": "CTS-V",
        "MR-S": "MR-S",
        "M5 (G90)": "M5 (G90)",
        "뱅퀴시 S": "Vanquish S",
        "타호": "Tahoe",
        "SLS AMG": "SLS AMG",
        "트래버스": "Traverse",
        "카이엔 (PO536)": "Cayenne (PO536)",
        "NX350h 2세대": "NX350h 2nd Gen",
        "328 GTB": "328 GTB",
        "그랑 콜레오스": "Grand Koleos",
        "EQS V297": "EQS V297",
        "코란도 EV (이모션)": "Korando EV (e-Motion)",
        "엑시지": "Exige",
        "플라잉스퍼 2세대": "Flying Spur 2nd Gen",
        "57s": "57s",
        "아리스토": "Aristo",
        "EQB X243": "EQB X243",
        "G90 (RS4)": "G90 (RS4)",
        "디 올 뉴 니로 EV": "The All New Niro EV",
        "뉴 티구안": "New Tiguan",
        "RX350": "RX350",
        "GLC-클래스 X254": "GLC-Class X254",
        "G80": "G80",
        "M3 (G80)": "M3 (G80)",
        "K5 2세대": "K5 2nd Gen",
        "E-클래스 W212": "E-Class W212",
        "308 3세대": "308 3rd Gen",
        "EQS SUV X296": "EQS SUV X296",
        "더 뉴 그랜드 스타렉스": "The New Grand Starex",
        "M4 (G82)": "M4 (G82)",
        "랭글러 (JK)": "Wrangler (JK)",
        "SQ5": "SQ5",
        "시로코": "Scirocco",
        "뉴콩코드": "New Concorde",
        "팰리세이드 (LX3)": "Palisade (LX3)",
        "레인지로버 5세대": "Range Rover 5th Gen",
        "더 뉴 QM6": "The New QM6",
        "시에나 4세대": "Sienna 4th Gen",
        "더 뉴 모닝 (JA)": "The New Morning (JA)",
        "A6 (C8)": "A6 (C8)",
        "SM3 네오": "SM3 Neo",
        "RS3 (8Y)": "RS3 (8Y)",
        "i30(신형)": "i30 (New Model)",
        "뉴 스타일 코란도 C": "New Style Korando C",
        "iX3": "iX3",
        "F8 스파이더": "F8 Spider",
        "599 GTB": "599 GTB",
        "우루스": "Urus",
        "2시리즈 액티브 투어러 (U06)": "2 Series Active Tourer (U06)",
        "CTS 2세대": "CTS 2nd Gen",
        "임프레자": "Impreza",
        "XM3": "XM3",
        "스타렉스": "Starex",
        "에미라": "Emira",
        "마티즈 클래식": "Matiz Classic",
        "아반떼": "Avante",
        "500e": "500e",
        "S-클래스": "S-Class",
        "체어맨 H": "Chairman H",
        "쿠퍼 쿠페": "Cooper Coupe",
        "SSR": "SSR",
        "쿠퍼 C 4세대": "Cooper C 4th Gen",
        "X2 (F39)": "X2 (F39)",
        "포투 카브리오": "Fortwo Cabrio",
        "쏘나타 II": "Sonata II",
        "New XJ": "New XJ",
        "뉴 투싼 ix": "New Tucson ix",
        "Q2": "Q2",
        "쿠퍼 일렉트릭": "Cooper Electric",
        "투아렉": "Touareg",
        "S-TYPE": "S-TYPE",
        "Q7 (4M)": "Q7 (4M)",
        "CT4": "CT4",
        "XC90 2세대": "XC90 2nd Gen",
        "푸가": "Fuga",
        "리릭": "Lyric",
        "N-ONE": "N-ONE",
        "트랙스 크로스오버": "Trax Crossover",
        "더 뉴 아반떼 하이브리드 (CN7)": "The New Avante Hybrid (CN7)",
        "CTS 3세대": "CTS 3rd Gen",
        "NX200t": "NX200t",
        "사이버트럭": "Cybertruck",
        "더 뉴 K8": "The New K8",
        "QM3": "QM3",
        "i30 cw": "i30 CW",
        "허머EV": "Hummer EV",
        "레인지로버 이보크": "Range Rover Evoque",
        "RX500h 5세대": "RX500h 5th Gen",
        "RX450h 4세대": "RX450h 4th Gen",
        "쏘나타 하이브리드 (DN8)": "Sonata Hybrid (DN8)",
        "리갈": "Regal",
        "5시리즈 GT (F07)": "5 Series GT (F07)",
        "600LT": "600LT",
        "아반떼 MD": "Avante MD",
        "JX35": "JX35",
        "뉴모닝": "New Morning",
        "RS7": "RS7",
        "그레나디어": "Grenadier",
        "MDX": "MDX",
        "올 뉴 쏘렌토": "All New Sorento",
        "더 뉴 K7": "The New K7",
        "코펜": "Copen",
        "GS300": "GS300",
        "머스탱 7세대": "Mustang 7th Gen",
        "308 2세대": "308 2nd Gen",
        "F430": "F430",
        "RAV4": "RAV4",
        "XJ-6": "XJ-6",
        "7시리즈": "7 Series",
        "SM7 New Art": "SM7 New Art",
        "N-BOX": "N-BOX",
        "296 GTS": "296 GTS",
        "골프 6세대": "Golf 6th Gen",
        "SL-클래스": "SL-Class",
        "무라노": "Murano",
        "3시리즈 (E90)": "3 Series (E90)",
        "200 2세대": "200 2nd Gen",
        "SC430": "SC430",
        "티볼리 아머": "Tivoli Armor",
        "갤로퍼": "Galloper",
        "인사이트": "Insight",
        "싼타페 DM": "Santa Fe DM",
        "LC": "LC",
        "뉴 IS250": "New IS250",
        "Q30": "Q30",
        "사바나": "Savanna",
        "뉴 세브링": "New Sebring",
        "LS500h 5세대": "LS500h 5th Gen",
        "랜드크루저": "Land Cruiser",
        "포포 2세대": "Fortwo 2nd Gen",
        "RC350": "RC350",
        "GV80": "GV80",
        "토레스": "Torres",
        "카니발 4세대": "Carnival 4th Gen",
        "아반떼 AD": "Avante AD",
        "7시리즈 (F01)": "7 Series (F01)",
        "NF 쏘나타": "NF Sonata",
        "570S": "570S",
        "488 스파이더": "488 Spider",
        "세이블": "Sable",
        "CL-클래스 C140": "CL-Class C140",
        "윈스톰": "Winstorm",
        "i40": "i40",
        "로버 미니": "Rover Mini",
        "FX30d": "FX30d",
        "스포티지 더 볼드": "Sportage The Bold",
        "레인지로버 벨라": "Range Rover Velar",
        "5시리즈": "5 Series",
        "XF (X260)": "XF (X260)",
        "GLB-클래스 X247": "GLB-Class X247",
        "812 슈퍼패스트": "812 Superfast",
        "308 GTS": "308 GTS",
        "2008 2세대": "2008 2nd Gen",
        "E-클래스 W213": "E-Class W213",
        "스펙트라": "Spectra",
        "미라지노": "Miragino",
        "GT": "GT",
        "H3": "H3",
        "라세드": "Laceda",
        "Q5": "Q5",
        "ES300h 7세대": "ES300h 7th Gen",
        "3008 2세대": "3008 2nd Gen",
        "GTC4 루쏘": "GTC4 Lusso",
        "더 뉴 벨로스터": "The New Veloster",
        "쿠퍼 S 클럽맨": "Cooper S Clubman",
        "다코타": "Dakota",
        "솔라라": "Solara",
        "셀리카": "Celica",
        "코나 하이브리드": "Kona Hybrid",
        "M8 (G15)": "M8 (G15)",
        "크로스파이어": "Crossfire",
        "더 뉴 아베오 해치백": "The New Aveo Hatchback",
        "XJ-8": "XJ-8",
        "더 럭셔리 그랜저": "The Luxury Grandeur",
        "체비밴": "Chevy Van",
        "더 뉴 트랙스": "The New Trax",
        "그랜드 카니발": "Grand Carnival",
        "New XF": "New XF",
        "RX350h 5세대": "RX350h 5th Gen",
        "XT6": "XT6",
        "308SW 2세대": "308SW 2nd Gen",
        "더 뉴 EV6": "The New EV6",
        "파나메라": "Panamera",
        "C30": "C30",
        "쿠퍼 S 4세대": "Cooper S 4th Gen",
        "뉴SM5": "New SM5",
        "엑스트레일": "X-Trail",
        "더 넥스트 스파크": "The Next Spark",
        "K5 하이브리드": "K5 Hybrid",
        "쏘울 부스터 EV": "Soul Booster EV",
        "NX300h": "NX300h",
        "M2 (F87)": "M2 (F87)",
        "카이엔": "Cayenne",
        "S-클래스 W223": "S-Class W223",
        "레간자": "Leganza",
        "스타리아": "Staria",
        "프리우스 V": "Prius V",
        "Q8 (4M)": "Q8 (4M)",
        "F8 트리뷰토": "F8 Tributo",
        "X5 (E70)": "X5 (E70)",
        "더 뉴 기아 레이": "The New Kia Ray",
        "티뷰론": "Tiburon",
        "넥쏘": "Nexo",
        "A8 (D5)": "A8 (D5)",
        "아벤타도르": "Aventador",
        "S8": "S8",
        "프론티어": "Frontier",
        "디펜더": "Defender",
        "NX450h+ 2세대": "NX450h+ 2nd Gen",
        "UX300e": "UX300e",
        "아르카나": "Arkana",
        "카이맨": "Cayman",
        "모델 Y": "Model Y",
        "캐니언": "Canyon",
        "V90 크로스컨트리": "V90 Cross Country",
        "GS460": "GS460",
        "쿠페": "Coupe",
        "페이톤": "Phaeton",
        "GX470": "GX470",
        "뱅퀴시": "Vanquish",
        "All New 마티즈": "All New Matiz",
        "아발란치": "Avalanche",
        "임팔라": "Impala",
        "랭글러 (TJ)": "Wrangler (TJ)",
        "더 뉴 투싼 (NX4)": "The New Tucson (NX4)",
        "X3M (G01)": "X3M (G01)",
        "3시리즈 (F30)": "3 Series (F30)",
        "로디우스 유로": "Rodius Euro",
        "체로키": "Cherokee",
        "포르테": "Forte",
        "FX35": "FX35",
        "익스플로러 6세대": "Explorer 6th Gen",
        "Q5 (FY)": "Q5 (FY)",
        "뮬산": "Mulsanne",
        "X3 (G45)": "X3 (G45)",
        "벤자": "Venza",
        "뉴 MKX": "New MKX",
        "SLK-클래스": "SLK-Class",
        "컨티넨탈": "Continental",
        "그랜저": "Grandeur",
        "골프 8세대": "Golf 8th Gen",
        "플라잉스퍼 3세대": "Flying Spur 3rd Gen",
        "퀘스트": "Quest",
        "Q8 e-트론 (GE)": "Q8 e-tron (GE)",
        "M5 (F90)": "M5 (F90)",
        "포르테 쿱": "Forte Coupe",
        "무르시엘라고": "Murciélago",
        "코나 일렉트릭": "Kona Electric",
        "X6M (G06)": "X6M (G06)",
        "뉴 IS200t": "New IS200t",
        "뉴 제타": "New Jetta",
        "500X": "500X",
        "Z8": "Z8",
        "308": "308",
        "CC": "CC",
        "올뉴어코드": "All New Accord",
        "쏘렌토 R": "Sorento R",
        "실버라도": "Silverado",
        "더 뉴 스포티지 5세대": "The New Sportage 5th Gen",
        "더 뉴 K5 3세대": "The New K5 3rd Gen",
        "무쏘 스포츠 칸 2세대": "Musso Sports Khan 2nd Gen",
        "CR-V 6세대": "CR-V 6th Gen",
        "뉴체어맨 W": "New Chairman W",
        "DS4": "DS4",
        "큐브": "Cube",
        "5시리즈 (G60)": "5 Series (G60)",
        "XC90": "XC90",
        "쿠퍼 컨버터블": "Cooper Convertible",
        "i7 (G70)": "i7 (G70)",
        "스토닉": "Stonic",
        "뉴 그랜저": "New Grandeur",
        "켄보 600": "Kenbo 600",
        "그랜저 하이브리드 (GN7)": "Grandeur Hybrid (GN7)",
        "레인지로버": "Range Rover",
        "아발론": "Avalon",
        "베뉴": "Venue",
        "엑센트(신형)": "Accent (New)",
        "더 뉴 파사트": "The New Passat",
        "제네시스 쿠페": "Genesis Coupe",
        "뉴 파사트": "New Passat",
        "CK 미니트럭": "CK MinTruck",
        "더 뉴 맥스크루즈": "The New Maxcruz",
        "뉴 TT": "New TT",
        "8시리즈 (G15)": "8 Series (G15)",
        "컴패스 2세대": "Compass 2nd Gen",
        "더 뉴 코란도 스포츠": "The New Korando Sports",
        "벤테이가": "Bentayga",
        "EX30": "EX30",
        "골프 7세대": "Golf 7th Gen",
        "파이브 헌드레드": "Five Hundred",
        "체어맨 H 뉴 클래식": "Chairman H New Classic",
        "뉴QM3": "New QM3",
        "500": "500",
        "TTS (8S)": "TTS (8S)",
        "500C": "500C",
        "골프 3세대": "Golf 3rd Gen",
        "캘리포니아": "California",
        "C35": "C35",
        "A4 (B9)": "A4 (B9)",
        "LS500 5세대": "LS500 5th Gen",
        "812 GTS": "812 GTS",
        "포레스터": "Forester",
        "쏘나타 (DN8)": "Sonata (DN8)",
        "코세어": "Corsair",
        "이쿼녹스": "Equinox",
        "Q60 (CV37)": "Q60 (CV37)",
        "쏘나타 하이브리드": "Sonata Hybrid",
        "S40": "S40",
        "K8": "K8",
        "XC60 2세대": "XC60 2nd Gen",
        "E-클래스 W124": "E-Class W124",
        "퓨전": "Fusion",
        "1시리즈 (F20)": "1 Series (F20)",
        "GLC-클래스 X253": "GLC-Class X253",
        "뉴체어맨": "New Chairman",
        "GLK-클래스 X204": "GLK-Class X204",
        "산타모": "Santamo",
        "엑셀": "Excel",
        "쏘나타 III": "Sonata III",
        "G80 (RG3)": "G80 (RG3)",
        "투싼": "Tucson",
        "ATS": "ATS",
        "쿠가 2세대": "Kuga 2nd Gen",
        "라피드": "Rapid",
        "Q4 e-트론 (F4)": "Q4 e-tron (F4)",
        "스프린터": "Sprinter",
        "A-클래스 W176": "A-Class W176",
        "쏘렌토 4세대": "Sorento 4th Gen",
        "X6M (F16)": "X6M (F16)",
        "에쿠스(신형)": "Equus (New)",
        "툰드라": "Tundra",
        "K3": "K3",
        "M4 (F82)": "M4 (F82)",
        "A-클래스 W177": "A-Class W177",
        "라보": "Labo",
        "던": "Den",
        "GLA-클래스 H247": "GLA-Class H247",
        "911 (992)": "911 (992)",
        "포르토피노": "Portofino",
        "파사트 GT(B8)": "Passat GT (B8)",
        "시에나": "Sienna",
        "QX56": "QX56",
        "아틀라스": "Atlas",
        "더 뉴 그랜저 IG": "The New Grandeur IG",
        "프리우스 C": "Prius C",
        "X5M (G05)": "X5M (G05)",
        "S70": "S70",
        "우라칸": "Huracan",
        "캡티바": "Captiva",
        "RS e-트론 GT": "RS e-tron GT",
        "뉴 캠리": "New Camry",
        "F-TYPE": "F-TYPE",
        "캠리 (XV70)": "Camry (XV70)",
        "tC": "tC",
        "코란도 훼미리": "Korando Family",
        "투싼 ix": "Tucson ix",
        "AMG GT": "AMG GT",
        "300C": "300C",
        "프레지오": "Pregio",
        "알티마 (L34)": "Altima (L34)",
        "Q6 e-트론 (GF)": "Q6 e-tron (GF)",
        "오딧세이": "Odyssey",
        "더 뉴 말리부": "The New Malibu",
        "5시리즈 (F10)": "5 Series (F10)",
        "ES300": "ES300",
        "마티즈 크리에이티브": "Matiz Creative",
        "타운카": "Town Car",
        "램밴": "Ram Van",
        "모하비 더 마스터": "Mohave The Master",
        "4Runner": "4Runner",
        "올 뉴 K3": "All New K3",
        "675LT": "675LT",
        "M37": "M37",
        "C-클래스 W205": "C-Class W205",
        "에비에이터 2세대": "Aviator 2nd Gen",
        "서버밴": "Suburban",
        "V60": "V60",
        "CT200h": "CT200h",
        "제네시스 DH": "Genesis DH",
        "K5 하이브리드 2세대": "K5 Hybrid 2nd Gen",
        "파크애비뉴": "Park Avenue",
        "컨티넨탈 GT 3세대": "Continental GT 3rd Gen",
        "수프라 5세대": "Supra 5th Gen",
        "마쯔다 6": "Mazda 6",
        "레조": "Rezo",
        "익스프레스밴": "Express Van",
        "R8": "R8",
        "더 뉴 아이오닉5": "The New Ioniq 5",
        "쿠퍼 D": "Cooper D",
        "Q50": "Q50",
        "에보라": "Evora",
        "DS5": "DS5",
        "K5 하이브리드 3세대": "K5 Hybrid 3rd Gen",
        "뉴 GS350": "New GS350",
        "EQA H243": "EQA H243",
        "올 뉴 모닝 (JA)": "All New Morning (JA)",
        "싼타페 CM": "Santa Fe CM",
        "올 뉴 모닝": "All New Morning",
        "수프라": "Supra",
        "머스탱": "Mustang",
        "제네시스": "Genesis",
        "뉴 그랜저 XG": "New Grandeur XG",
        "트랜짓": "Transit",
        "CLK-클래스 C209": "CLK-Class C209",
        "K7 프리미어 하이브리드": "K7 Premier Hybrid",
        "M3 (E36)": "M3 (E36)",
        "뉴엘란트라": "New Elantra",
        "토레스 EVX": "Torres EVX",
        "노틸러스 1세대": "Nautilus 1st Gen",
        "아이오닉6": "Ioniq 6",
        "575M": "575M",
        "뉴 GS200t": "New GS200t",
        "유콘": "Yukon",
        "더 뉴 K9 2세대": "The New K9 2nd Gen",
        "더 뉴 K3 쿱": "The New K3 Coupe",
        "올 뉴 투싼": "All New Tucson",
        "8시리즈": "8 Series",
        "베리 뉴 티볼리": "Very New Tivoli",
        "9-3 1세대": "9-3 1st Gen",
        "카렌스": "Carens",
        "X3 (E83)": "X3 (E83)",
        "더 뉴 토레스": "The New Torres",
        "XC40": "XC40",
        "MKS": "MKS",
        "디스커버리 5": "Discovery 5",
        "RCZ": "RCZ",
        "K3 쿱": "K3 Coupe",
        "i8": "i8",
        "V40": "V40",
        "뉴 A8": "New A8",
        "QX80": "QX80",
        "62": "62",
        "뉴 A6": "New A6",
        "스포티지 4세대": "Sportage 4th Gen",
        "뉴 A4": "New A4",
        "에스페로": "Espero",
        "쿠퍼 S 컨트리맨 3세대": "Cooper S Countryman 3rd Gen",
        "챌린저": "Challenger",
        "LS460L": "LS460L",
        "레전드 4세대": "Legend 4th Gen",
        "M5 (E60)": "M5 (E60)",
        "720S": "720S",
        "X4 (F26)": "X4 (F26)",
        "맥시마 (A36)": "Maxima (A36)",
        "LF 쏘나타 하이브리드": "LF Sonata Hybrid",
        "쿠퍼 로드스터": "Cooper Roadster",
        "i30": "i30",
        "줄리에타": "Giulietta",
        "3시리즈": "3 Series",
        "F150": "F150",
        "9-5 1세대": "9-5 1st Gen",
        "더 뉴 스포티지 5세대 하이브리드": "The New Sportage 5th Gen Hybrid",
        "DB9": "DB9",
        "더 뉴 티볼리": "The New Tivoli",
        "PT 크루저": "PT Cruiser",
        "뉴 S4": "New S4",
        "코란도 스포츠": "Korando Sports",
        "ID.4": "ID.4",
        "듀랑고": "Durango",
        "MKX 2세대": "MKX 2nd Gen",
        "FX50": "FX50",
        "더 뉴 i40 살룬": "The New i40 Saloon",
        "XT5": "XT5",
        "SM3 뉴 제너레이션": "SM3 New Generation",
        "코나 하이브리드 (SX2)": "Kona Hybrid (SX2)",
        "엘란": "Elan",
        "X3 (G01)": "X3 (G01)",
        "124 스파이더": "124 Spider",
        "뉴QM5": "New QM5",
        "뉴SM5 플래티넘": "New SM5 Platinum",
        "레인저 4세대": "Ranger 4th Gen",
        "뉴 A3": "New A3",
        "올 뉴 카렌스": "All New Carens",
        "B-클래스 W245": "B-Class W245",
        "크라운": "Crown",
        "어코드 10세대": "Accord 10th Gen",
        "올 뉴 렉스턴": "All New Rexton",
        "쏘나타 디 엣지(DN8)": "Sonata The Edge (DN8)",
        "i4": "i4",
        "7시리즈 (E65)": "7 Series (E65)",
        "카마로": "Camaro",
        "QM6": "QM6",
        "S60": "S60",
        "Q3": "Q3",
        "패스파인더 4세대": "Pathfinder 4th Gen",
        "익스플로러": "Explorer",
        "슈퍼살롱": "Supersalon",
        "컨티넨탈 GT 1세대": "Continental GT 1st Gen",
        "컨티넨탈 10세대": "Continental 10th Gen",
        "아반떼 XD": "Avante XD",
        "e-트론 GT": "e-tron GT",
        "파나메라 (971)": "Panamera (971)",
        "X1 (U11)": "X1 (U11)",
        "QM5 네오": "QM5 Neo",
        "무쏘 스포츠 2세대": "Musso Sports 2nd Gen",
        "블레이저": "Blazer",
        "뉴 CC": "New CC",
        "쿠퍼 D 클럽맨": "Cooper D Clubman",
        "뉴 IS300": "New IS300",
        "DS4 2세대": "DS4 2nd Gen",
        "크라운 크로스오버": "Crown Crossover",
        "올 뉴 K7 하이브리드": "All New K7 Hybrid",
        "R-클래스": "R-Class",
        "캐스퍼": "Casper",
        "쏘울 EV": "Soul EV",
        "뉴SM5(신형)": "New SM5 (New Model)",
        "랭글러 (YJ)": "Wrangler (YJ)",
        "뉴 다마스": "New Damas",
        "M56": "M56",
        "2시리즈 (F22)": "2 Series (F22)",
        "TT": "TT",
        "SQ8 (4M)": "SQ8 (4M)",
        "206CC": "206CC",
        "쿠퍼 S 쿠페": "Cooper S Coupe",
        "EV9": "EV9",
        "HR-V": "HR-V",
        "스포티지 5세대 하이브리드": "Sportage 5th Gen Hybrid",
        "볼트 EUV": "Bolt EUV",
        "EV6": "EV6",
        "508 2세대": "508 2nd Gen",
        "i3": "i3",
        "300ZX": "300ZX",
        "2시리즈 (G42)": "2 Series (G42)",
        "CR-Z": "CR-Z",
        "488 GTB": "488 GTB",
        "QX50": "QX50",
        "M35": "M35",
        "X1 (F48)": "X1 (F48)",
        "MC20": "MC20",
        "X5 (E53)": "X5 (E53)",
        "G-클래스 W463": "G-Class W463",
        "그랜드 체로키(WL)": "Grand Cherokee (WL)",
        "뉴 STS": "New STS",
        "XM (G09)": "XM (G09)",
        "DS7 크로스백": "DS7 Crossback",
        "슈퍼 렉스턴": "Super Rexton",
        "더 뉴 K3 2세대": "The New K3 2nd Gen",
        "디 올 뉴 니로": "The All New Niro",
        "토러스": "Taurus",
        "스팅어 마이스터": "Stinger Meister",
        "엑센트": "Accent",
        "오피러스 프리미엄": "Opirus Premium",
        "더 뉴 캐스퍼": "The New Casper",
        "E-Series": "E-Series",
        "뉴 EF 쏘나타": "New EF Sonata",
        "가야르도": "Gallardo",
        "E-클래스 W211": "E-Class W211",
        "A1": "A1",
        "GLA-클래스 X156": "GLA-Class X156",
        "ST1": "ST1",
        "더 비틀": "The Beetle",
        "그랜저 XG": "Grandeur XG",
        "네비게이터 4세대": "Navigator 4th Gen",
        "308SW": "308SW",
        "이스케이프": "Escape",
        "포투 쿠페": "Fortwo Coupe",
        "S90": "S90",
        "SM6": "SM6",
        "911": "911",
        "아반떼 쿠페": "Avante Coupe",
        "M3 (F80)": "M3 (F80)",
        "EF 쏘나타": "EF Sonata",
        "그랜드 C4 피카소": "Grand C4 Picasso",
        "말리부": "Malibu",
        "액티언 스포츠": "Actyon Sports",
        "올 뉴 SRX": "All New SRX",
        "캠리": "Camry",
        "아반떼 (CN7)": "Avante (CN7)",
        "올 뉴 콜로라도": "All New Colorado",
        "브레라": "Brera",
        "C4 칵투스": "C4 Cactus",
        "K7 프리미어": "K7 Premier",
        "그란카브리오": "GranCabrio",
        "레인지로버 스포츠": "Range Rover Sport",
        "RS5 (F5)": "RS5 (F5)",
        "올란도": "Orlando",
        "CL-클래스 C215": "CL-Class C215",
        "올 뉴 아반떼": "All New Avante",
        "레보그": "Levorg",
        "SL-클래스 R232": "SL-Class R232",
        "TTS": "TTS",
        "DBX": "DBX",
        "XE": "XE",
        "엔터프라이즈": "Enterprise",
        "더 뉴 쏘렌토 4세대": "The New Sorento 4th Gen",
        "에이스맨 1세대": "AceMan 1st Gen",
        "타스만": "Tasman",
        "6시리즈 GT (G32)": "6 Series GT (G32)",
        "SQ7 (4M)": "SQ7 (4M)",
        "쏘렌토": "Sorento",
        "EV3": "EV3",
        "그레칼레": "Grecale",
        "익스퍼트 티피": "Expert TPi",
        "렉스턴 뉴 아레나": "Rexton New Arena",
        "e-2008 2세대": "e-2008 2nd Gen",
        "무라노 (Z52)": "Murano (Z52)",
        "다임러": "Daimler",
        "아베오 해치백": "Aveo Hatchback",
        "508": "508",
        "오피러스": "Opirus",
        "더 뉴 그랜저 IG 하이브리드": "The New Grandeur IG Hybrid",
        "CR-V": "CR-V",
        "XC70": "XC70",
        "젠트라 X": "Gentra X",
        "207RC": "207RC",
        "올 뉴 쏘울": "All New Soul",
        "랜서 에볼루션": "Lancer Evolution",
        "코나 (SX2)": "Kona (SX2)",
        "CT6": "CT6",
        "아토스": "Atos",
        "팰리세이드": "Palisade",
        "레토나": "Retona",
        "EOS": "EOS",
        "고스트 2세대": "Ghost 2nd Gen",
        "SF90 스파이더": "SF90 Spider",
        "207CC": "207CC",
        "SM7 노바": "SM7 Nova",
        "몬데오 4세대": "Mondeo 4th Gen",
        "볼트 EV": "Bolt EV",
        "S5": "S5",
        "S6": "S6",
        "M-클래스 W163": "M-Class W163",
        "K5 3세대": "K5 3rd Gen",
        "파일럿 3세대": "Pilot 3rd Gen",
        "62s": "62s",
        "9-3 2세대": "9-3 2nd Gen",
        "티볼리": "Tivoli",
        "DS3": "DS3",
        "뉴 카이엔": "New Cayenne",
        "MX-5 MIATA": "MX-5 Miata",
        "190-클래스": "190-Class",
        "뉴 GS450h": "New GS450h",
        "RX450h+ 5세대": "RX450h+ 5th Gen",
        "7시리즈 (G70)": "7 Series (G70)",
        "AMG GT C192": "AMG GT C192",
        "뉴 SL-클래스": "New SL-Class",
        "알티마": "Altima",
        "투스카니": "Tuscani",
        "티록": "T-Roc",
        "쿠퍼 SD 컨트리맨": "Cooper SD Countryman",
        "M5 (F10)": "M5 (F10)",
        "M6 (E63)": "M6 (E63)",
        "SLC-클래스 R172": "SLC-Class R172",
        "그랜저 IG 하이브리드": "Grandeur IG Hybrid",
        "네비게이터": "Navigator",
        "액티언 2세대": "Actyon 2nd Gen",
        "쿠퍼 클럽맨": "Cooper Clubman",
        "R1": "R1",
        "티구안 올스페이스": "Tiguan Allspace",
        "F350": "F350",
        "S7 (4K)": "S7 (4K)",
        "Q60": "Q60",
        "F355": "F355",
        "TL": "TL",
        "SRX": "SRX",
        "그란투리스모": "GranTurismo",
        "투싼 하이브리드 (NX4)": "Tucson Hybrid (NX4)",
        "뷰티풀 코란도": "Beautiful Korando",
        "아반떼 하이브리드": "Avante Hybrid",
        "고스트": "Ghost",
        "X2 (U10)": "X2 (U10)",
        "X7 (G07)": "X7 (G07)",
        "마르샤": "Marcia",
        "코나 일렉트릭 (SX2)": "Kona Electric (SX2)",
        "시빅": "Civic",
        "렉스턴 II": "Rexton II",
        "크레도스": "Credos",
        "더 뉴 K8 하이브리드": "The New K8 Hybrid",
        "차저": "Charger",
        "K7": "K7",
        "쿠퍼 S": "Cooper S",
        "일렉트리파이드 GV70": "Electrified GV70",
        "노틸러스 2세대": "Nautilus 2nd Gen",
        "무쏘 스포츠": "Musso Sports",
        "LM 2세대": "LM 2nd Gen",
        "New CR-V": "New CR-V",
        "레인지로버 4세대": "Range Rover 4th Gen",
        "GLE-클래스 W166": "GLE-Class W166",
        "370Z": "370Z",
        "아웃백": "Outback",
        "레인지로버 스포츠 2세대": "Range Rover Sport 2nd Gen",
        "콜벳": "Corvette",
        "CR-V 5세대": "CR-V 5th Gen",
        "플라잉스퍼 1세대": "Flying Spur 1st Gen",
        "트레일블레이저": "Trailblazer",
        "에비에이터 1세대": "Aviator 1st Gen",
        "캠리 (XV80)": "Camry (XV80)",
        "SEL/SEC": "SEL/SEC",
        "TT (8S)": "TT (8S)",
        "K5": "K5",
        "더 뉴 쏘렌토": "The New Sorento",
        "GT-R": "GT-R",
        "뉴렉스턴": "New Rexton",
        "액티언": "Actyon",
        "7시리즈 (G11)": "7 Series (G11)",
        "아베오 세단": "Aveo Sedan",
        "로그 (S35)": "Rogue (S35)",
        "뉴 ES300h": "New ES300h",
        "iQ": "iQ",
        "K9": "K9",
        "모하비": "Mohave",
        "SM5 뉴 임프레션": "SM5 New Impression",
        "벨로스터 (JS)": "Veloster (JS)",
        "All New SM7": "All New SM7",
        "488 피스타": "488 Pista",
        "더 뉴 셀토스": "The New Seltos",
        "S60 3세대": "S60 3rd Gen",
        "컨티넨탈 GT 4세대": "Continental GT 4th Gen",
        "e-트론": "e-tron",
        "CLA-클래스 C118": "CLA-Class C118",
        "1시리즈 (E82)": "1 Series (E82)",
        "New 스포티지": "New Sportage",
        "쏠라티": "Solati",
        "프리우스": "Prius",
        "Q3 (F3)": "Q3 (F3)",
        "아스트로밴": "Astrovan",
        "포니투": "Pony II",
        "스타렉스 점보": "Starex Jumbo",
        "CL-클래스 C216": "CL-Class C216",
        "Q5 (80A)": "Q5 (80A)",
        "X1 (E84)": "X1 (E84)",
        "싼타페 TM": "SantaFe TM",
        "H2": "H2",
        "프리랜더2": "Freelander 2",
        "CT5": "CT5",
        "408": "408",
        "베르나(신형)": "Verna (New)",
        "뉴 라보": "New Labo",
        "DBS": "DBS",
        "쿠퍼 SD": "Cooper SD",
        "V8 Vantage": "V8 Vantage",
        "캐스퍼 일렉트릭": "Casper Electric",
        "X6 (F16)": "X6 (F16)",
        "그랜드 체로키": "Grand Cherokee",
        "쿠퍼 S 로드스터": "Cooper S Roadster",
        "A7": "A7",
        "아이오닉 일렉트릭": "Ioniq Electric",
        "A5 (F5)": "A5 (F5)",
        "노아": "Noah",
        "Z4 (E85)": "Z4 (E85)",
        "갤로퍼 2": "Galloper 2",
        "토스카": "Tosca",
        "더 넥스트 이쿼녹스": "The Next Equinox",
        "RS5": "RS5",
        "맥스크루즈": "Maxcruz",
        "파나메라 (972)": "Panamera (972)",
        "라세티 프리미어": "Lacetti Premier",
        "프라이드": "Pride",
        "XKR-S": "XKR-S",
        "C70": "C70",
        "EX35": "EX35",
        "뉴 투아렉": "New Touareg",
        "QM5": "QM5",
        "DS3 카브리오": "DS3 Cabrio",
        "모델 X": "Model X",
        "더 뉴 티볼리 에어": "The New Tivoli Air",
        "C-클래스 W206": "C-Class W206",
        "랜서": "Lancer",
        "V60 크로스컨트리": "V60 Cross Country",
        "더 뉴 K5 2세대": "The New K5 2nd Gen",
        "SM7": "SM7",
        "2시리즈 액티브 투어러 (F45)": "2 Series Active Tourer (F45)",
        "MKC": "MKC",
        "CLK-클래스 C208": "CLK-Class C208",
        "트위지": "Twizy",
        "제타 7세대": "Jetta 7th Gen",
        "컬리넌": "Cullinan",
        "더 뉴 팰리세이드": "The New Palisade",
        "더 뉴 카마로": "The New Camaro",
        "스포티지 5세대": "Sportage 5th Gen",
        "알파드 4세대": "Alphard 4th Gen",
        "EQE SUV X294": "EQE SUV X294",
        "아반떼 HD": "Avante HD",
        "X6 (E71)": "X6 (E71)",
        "파크타운": "Parktown",
        "G-클래스 W465": "G-Class W465",
        "UX250h": "UX250h",
        "308CC": "308CC",
        "디스커버리 스포츠 2세대": "Discovery Sport 2nd Gen",
        "S7": "S7",
        "더 뉴 아이오닉 하이브리드": "The New Ioniq Hybrid",
        "더 뉴 K5 하이브리드 2세대": "The New K5 Hybrid 2nd Gen",
        "GL-클래스 X166": "GL-Class X166",
        "어코드": "Accord",
        "에스티마": "Estima",
        "LS460": "LS460",
        "EQE V295": "EQE V295",
        "86": "86",
        "올 뉴 프라이드": "All New Pride",
        "카니발 R": "Carnival R",
        "아토 3": "Ato 3",
        "마칸": "Macan",
        "포커스": "Focus",
        "올로드 콰트로": "Allroad Quattro",
        "더 뉴 카니발": "The New Carnival",
        "티구안": "Tiguan",
        "C3 에어크로스": "C3 Aircross",
        "더 뉴 프라이드": "The New Pride",
        "6시리즈 (E63)": "6 Series (E63)",
        "세나": "Sena",
        "캐딜락 CT4": "Cadillac CT4",
        "벤틀리 컨티넨탈 플라잉스퍼 3세대": "Bentley Continental Flying Spur 3rd Gen",
        "A8 (D4)": "A8 (D4)",
        "뉴 라세티": "New Lacetti",
        "NX300h": "NX300h",
        "스팅어": "Stinger",
        "마크 X": "Mark X",
        "더 뉴 코나": "The New Kona",
        "캐딜락 CT5": "Cadillac CT5",
        "G90": "G90",
        "뉴 카렌스": "New Carens",
        "포르쉐 911 (992)": "Porsche 911 (992)",
        "QM6": "QM6",
        "Q7 (4M)": "Q7 (4M)",
        "트랙스": "Trax",
        "뉴 투싼 (TL)": "New Tucson (TL)",
        "더 뉴 싼타페": "The New SantaFe",
        "G70": "G70",
        "E클래스 W213": "E-Class W213",
        "G20": "G20",
        "XC90": "XC90",
        "아이오닉 5": "Ioniq 5",
        "아반떼 CN7": "Avante CN7",
        "캐스퍼": "Casper",
        "더 뉴 아반떼": "The New Avante",
        "ES300h": "ES300h",
        "투싼 (NX4)": "Tucson (NX4)",
        "GV70": "GV70",
        "쏘나타 DN8": "Sonata DN8",
        "GV80": "GV80",
        "포르테": "Forte",
        "G80": "G80",
        "코나 N": "Kona N",
        "팰리세이드": "Palisade",
        "싼타페 TM 페이스리프트": "SantaFe TM Facelift",
        "그랜저 IG": "Grandeur IG",
        "스포티지 QL": "Sportage QL",
        "스포티지 NQ5": "Sportage NQ5",
        "셀토스": "Seltos",
        "카니발 KA4": "Carnival KA4",
        "베라크루즈": "Veracruz",
        "투싼 TL": "Tucson TL",
        "투싼 LM": "Tucson LM",
        "i30": "i30",
        "쏘렌토 MQ4": "Sorento MQ4",
        "쏘렌토 UM": "Sorento UM",
        "쏘렌토 XM": "Sorento XM",
        "카니발 KA2": "Carnival KA2",
        "코란도": "Korando",
        "티볼리": "Tivoli",
        "렉스턴": "Rexton",
        "모하비 더 마스터": "Mohave The Master",
        "맥스크루즈 더 프라임": "Maxcruz The Prime",
        "베라크루즈 2세대": "Veracruz 2nd Gen",
        "투싼 ix": "Tucson ix",
        "투싼 LM 페이스리프트": "Tucson LM Facelift",
        "투싼 TL 페이스리프트": "Tucson TL Facelift",
        "싼타페 CM": "SantaFe CM",
        "싼타페 DM": "SantaFe DM",
        "싼타페 TM 더 프라임": "SantaFe TM The Prime",
        "싼타페 더 프라임": "SantaFe The Prime",
        "코나 NX4": "Kona NX4",
        "코나 페이스리프트": "Kona Facelift",
        "투싼 N": "Tucson N",
        "베뉴": "Venue",
        "아반떼 HD 페이스리프트": "Avante HD Facelift",
        "아반떼 MD": "Avante MD",
        "아반떼 AD": "Avante AD",
        "아반떼 CN7 페이스리프트": "Avante CN7 Facelift",
        "더 뉴 아반떼 CN7": "The New Avante CN7",
        "i20": "i20",
        "i10": "i10",
        "투싼 NQ5": "Tucson NQ5",
        "투싼 NX4 페이스리프트": "Tucson NX4 Facelift",
        "쏘나타 LF": "Sonata LF",
        "쏘나타 DN8 페이스리프트": "Sonata DN8 Facelift",
        "쏘나타 뉴 라이즈": "Sonata New Rise",
        "그랜저 HG": "Grandeur HG",
        "그랜저 IG 페이스리프트": "Grandeur IG Facelift",
        "그랜저 GN7": "Grandeur GN7",
        "쏘렌토 MQ4 페이스리프트": "Sorento MQ4 Facelift",
        "쏘렌토 MQ4 더 프라임": "Sorento MQ4 The Prime",
        "카니발 KA4 페이스리프트": "Carnival KA4 Facelift",
        "카니발 KA4 더 프라임": "Carnival KA4 The Prime",
        "카니발 KA2 페이스리프트": "Carnival KA2 Facelift",
        "카니발 KA2 더 프라임": "Carnival KA2 The Prime",
        "스포티지 NQ5 페이스리프트": "Sportage NQ5 Facelift",
        "스포티지 NQ5 더 프라임": "Sportage NQ5 The Prime",
        "셀토스 페이스리프트": "Seltos Facelift",
        "셀토스 더 프라임": "Seltos The Prime",
        "더 뉴 K5 하이브리드 3세대": "The New K5 Hybrid 3rd Gen",
        "타코마": "Tacoma",
        "그랜저 뉴 럭셔리": "Grandeur New Luxury",
        "레니게이드": "Renegade",
        "브룩랜즈": "Brooklands",
        "레거시": "Legacy",
        "쏘나타 뉴 라이즈 하이브리드": "Sonata New Rise Hybrid",
        "소버린": "Sovereign",
        "G-클래스 W463b": "G-Class W463b",
        "RSQ8 (4M)": "RSQ8 (4M)",
        "무쏘": "Musso",
        "더 뉴 니로": "The New Niro",
        "니로": "Niro",
        "더 뉴 아반떼 AD": "The New Avante AD",
        "뉴코란도 C": "New Korando C",
        "그랜저 IG": "Grandeur IG",
        "더 뉴 아반떼": "The New Avante",
        "조에": "Zoe",
        "GLS-클래스 X167": "GLS-Class X167",
        "투아렉 3세대": "Touareg 3rd Gen",
        "Q7": "Q7",
        "에스컬레이드": "Escalade",
        "IS250": "IS250",
        "뉴 GS250": "New GS250",
        "비스토": "Bisto",
        "콰트로포르테": "Quattroporte",
        "YF 쏘나타": "YF Sonata",
        "207GT": "207GT",
        "3시리즈 (G20)": "3 Series (G20)",
        "쿠퍼 D 컨트리맨": "Cooper D Countryman",
        "더 뉴 쏘울": "The New Soul",
        "뉴SM3": "New SM3",
        "테라칸": "Terracan",
        "익스페디션": "Expedition",
        "G90": "G90",
        "S6 (C8)": "S6 (C8)",
        "더 뉴 렉스턴 스포츠": "The New Rexton Sports",
        "Z4 (E89)": "Z4 (E89)",
        "XC60": "XC60",
        "쏘울": "Soul",
        "허슬러": "Hustler",
        "360": "360",
        "2시리즈 그란쿠페 (F44)": "2 Series Gran Coupe (F44)",
        "A7 (4K)": "A7 (4K)",
        "M-클래스 W166": "M-Class W166",
        "X5 (F15)": "X5 (F15)",
        "알토": "Alto",
        "레이스": "Race",
        "디스커버리 스포츠": "Discovery Sport",
        "F12 베를리네타": "F12 Berlinetta",
        "CLE-클래스 C236": "CLE-Class C236",
        "S-클래스 W222": "S-Class W222",
        "그랜드 C4 스페이스투어러": "Grand C4 SpaceTourer",
        "올 뉴 크루즈": "All New Cruze",
        "티볼리 에어": "Tivoli Air",
        "트랙스": "Trax",
        "쿠퍼 SD 클럽맨": "Cooper SD Clubman",
        "RS7 (4K)": "RS7 (4K)",
        "XF": "XF",
        "포투 쿠페 3세대": "ForTwo Coupe 3rd Gen",
        "코롤라": "Corolla",
        "마스터": "Master",
        "MKZ": "MKZ",
        "크로스투어": "Crosstour",
        "캘리버": "Caliber",
        "그랜저 HG": "Grandeur HG",
        "더 뉴 아베오 세단": "The New Aveo Sedan",
        "G37": "G37",
        "DB12": "DB12",
        "C-클래스 W204": "C-Class W204",
        "디스커버리 2": "Discovery 2",
        "더 뉴 트레일블레이저": "The New Trailblazer",
        "QX30": "QX30",
        "컨티넨탈 GT 2세대": "Continental GT 2nd Gen",
        "R8 (4S)": "R8 (4S)",
        "아이오닉9": "Ioniq 9",
        "I-PACE": "I-PACE",
        "아발론 5세대": "Avalon 5th Gen",
        "멀티밴": "Multivan",
        "S80": "S80",
        "뉴 볼트 EV": "New Bolt EV",
        "SM5 노바": "SM5 Nova",
        "XT4": "XT4",
        "X-TYPE": "X-TYPE",
        "e-208 2세대": "e-208 2nd Gen",
        "57": "57",
        "CK 미니밴": "CK Minivan",
        "B-클래스 W246": "B-Class W246",
        "아반떼 하이브리드 (CN7)": "Avante Hybrid (CN7)",
        "싼타페": "SantaFe",
        "K8 하이브리드": "K8 Hybrid",
        "X6 (G06)": "X6 (G06)",
        "S4 (B9)": "S4 (B9)",
        "아이고": "Aigo",
        "콜로라도": "Colorado",
        "XK": "XK",
        "드빌": "DeVille",
        "C40 리차지": "C40 Recharge",
        "V12 Vantage": "V12 Vantage",
        "커맨더": "Commander",
        "4시리즈 (F32)": "4 Series (F32)",
        "캐시카이 2세대": "Qashqai 2nd Gen",
        "올 뉴 말리부": "All New Malibu",
        "쿠퍼 컨트리맨 일렉트릭 3세대": "Cooper Countryman Electric 3rd Gen",
        "어코드 11세대": "Accord 11th Gen",
        "뉴 MKZ": "New MKZ",
        "GV80 쿠페": "GV80 Coupe",
        "올 뉴 카마로": "All New Camaro",
        "코란도 C": "Korando C",
        "일렉트리파이드 G80 (RG3)": "Electrified G80 (RG3)",
        "로체 이노베이션": "Lotre Innovation",
        "올 뉴 카니발": "All New Carnival",
        "296 GTB": "296 GTB",
        "SF90 스트라달레": "SF90 Stradale",
        "체로키(KL)": "Cherokee (KL)",
        "다마스 II": "Damas II",
        "508SW 2세대": "508SW 2nd Gen",
        "1M (E82)": "1M (E82)",
        "디스커버리": "Discovery",
        "G70": "G70",
        "뉴 ES350": "New ES350",
        "i30 (PD)": "i30 (PD)",
        "마칸 EV": "Macan EV",
        "EQ900": "EQ900",
        "G35": "G35",
        "더 뉴 K9": "The New K9",
        "X5 (G05)": "X5 (G05)",
        "폴스타 2": "Polestar 2",
        "엘리스": "Elise",
        "DS3 크로스백": "DS3 Crossback",
        "박스터": "Boxster",
        "레이": "Ray",
        "디스커버리 3": "Discovery 3",
        "더 뉴 코나": "The New Kona",
        "UX300h": "UX300h",
        "더 뉴 아반떼 (CN7)": "The New Avante (CN7)",
        "랭글러 (JL)": "Wrangler (JL)",
        "V60 크로스컨트리 2세대": "V60 Cross Country 2nd Gen",
        "글래디에이터 (JT)": "Gladiator (JT)",
        "아테온": "Arteon",
        "458": "458",
        "파일럿": "Pilot",
        "뉴 쏘렌토 R": "New Sorento R",
        "LS600hL": "LS600hL",
        "어메이징 뉴 크루즈5": "Amazing New Cruze5",
        "H1": "H1",
        "클리오": "Clio",
        "E-PACE": "E-PACE",
        "퍼시피카": "Pacifica",
        "싼타페 더 프라임": "SantaFe The Prime",
        "RX450h": "RX450h",
        "로체": "Lotre",
        "엘레트라": "Elantra",
        "더 뉴 스포티지 R": "The New Sportage R",
        "리얼 뉴 콜로라도": "Real New Colorado",
        "GV60": "GV60",
    }
}



OPTIONS = {
    'CAR': {
        "001": "Антиблокировочная система (ABS)",
        "002": "Электронно-регулируемая подвеска (ECS)",
        "003": "CD-проигрыватель",
        "004": "Передний мультимедиа-экран",
        "005": "Навигационная система",
        "006": "Электропривод замков дверей",
        "007": "Электростеклоподъёмники",
        "008": "Гидроусилитель руля",
        "010": "Люк",
        "014": "Кожаный салон",
        "015": "Центральный замок с ДУ",
        "017": "Легкосплавные диски",
        "019": "Система курсовой устойчивости (TCS)",
        "020": "Боковые подушки безопасности",
        "021": "Электропривод передних сидений",
        "022": "Подогрев передних и задних сидений",
        "023": "Климат-контроль",
        "024": "Складывающиеся боковые зеркала с электроприводом",
        "026": "Фронтальные подушки безопасности",
        "027": "Фронтальные подушки безопасности",
        "029": "Фары (ксенон/LED)",
        "030": "Электрохромное зеркало заднего вида",
        "031": "Мультируль",
        "032": "Датчики парковки (перед/зад)",
        "033": "Система контроля давления в шинах (TPMS)",
        "034": "Вентилируемые передние сиденья",
        "035": "Электропривод передних сидений",
        "051": "Сиденья с памятью настроек",
        "054": "Задний мультимедиа-экран",
        "055": "Электронная система стабилизации (ESC)",
        "056": "Шторки безопасности (Air Curtain)",
        "057": "Смарт-ключ",
        "058": "Камера заднего вида",
        "059": "Электропривод багажника",
        "062": "Рейлинги на крыше",
        "063": "Подогрев передних и задних сидений",
        "068": "Круиз-контроль (обычный/адаптивный)",
        "071": "AUX-вход",
        "072": "USB-порт",
        "074": "Hi-pass (автооплата дорог)",
        "075": "Фары (ксенон/LED)",
        "077": "Вентилируемые передние сиденья",
        "078": "Сиденья с памятью настроек",
        "079": "Круиз-контроль (обычный/адаптивный)",
        "080": "Электропривод дверей",
        "081": "Датчик дождя",
        "082": "Подогрев рулевого колеса",
        "083": "Электрорегулировка рулевой колонки",
        "084": "Подрулевые лепестки переключения передач",
        "085": "Датчики парковки (перед/зад)",
        "086": "Система контроля слепых зон (BSW)",
        "087": "Камеры кругового обзора (360°)",
        "088": "Система удержания в полосе (LDWS)",
        "089": "Электропривод задних сидений",
        "090": "Вентилируемые задние сиденья",
        "091": "Массажные сиденья",
        "092": "Солнцезащитные шторки для задних сидений",
        "093": "Солнцезащитные шторки для задних сидений",
        "094": "Электронный стояночный тормоз (EPB)",
        "095": "Проекционный дисплей (HUD)",
        "096": "Bluetooth",
        "097": "Автоматический свет",
    },

    'TRUCK': {
        "001": "Гидроборт (Power Gate)",
        "002": "Легкосплавные диски",
        "003": "Люк",
        "004": "Складывающиеся боковые зеркала с электроприводом",
        "005": "Электропривод откидной кабины",
        "006": "Спойлер на крыше",
        "007": "ВОМ (вал отбора мощности)",
        "008": "Электрический сигнал (клаксон)",
        "009": "Газовый компрессор",  # в API какой-то греческий???
        "010": "Система снижения дымности",
        "011": "Мультируль",
        "012": "Гидроусилитель руля",
        "013": "Вентилируемые передние сиденья",
        "014": "Кожаный салон",
        "015": "Подогрев передних сидений",
        "016": "Подогреваемая спальная полка",
        "017": "ECM (электронный блок управления двигателем)",
        "018": "Ретардер (гидравлический тормоз-замедлитель)",
        "019": "Антиблокировочная система (ABS)",
        "020": "ASR/TCS (система против пробуксовки)",
        "021": "Пневматические тормоза",
        "022": "Система контроля давления в шинах (TPMS)",
        "023": "EHS (помощь при старте на подъеме)",
        "024": "Тахометр",
        "025": "Подушка безопасности (водительская)",
        "026": "Камера заднего вида",
        "027": "Кондиционер (ручной)",
        "028": "Климат-контроль",
        "029": "Отопитель/кондиционер Mushidong",  # брендовый, оставил оригинал
        "030": "Центральный замок с ДУ",
        "031": "Электростеклоподъёмники",
        "032": "Круиз-контроль",
        "033": "CD-проигрыватель",
        "034": "Навигационная система",
        "035": "AUX-вход",
        "036": "USB-порт",
        "037": "Холодильник",
    }
}